DataFabricTech/DataFabricVisual

project/ui/frontend/common/nuxt.config.ts
=> [FAB2023-488] Storybook 이슈

project/ui/frontend/common/pages/index.vue
[FAB2023-488](https://mobigen.atlassian.net/browse/FAB2023-488)
- [FAB2023-569](https://mobigen.atlassian.net/browse/FAB2023-569)
[FAB2023-488]: https://mobigen.atlassian.net/browse/FAB2023-488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-569]: https://mobigen.atlassian.net/browse/FAB2023-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-488] feat: 메뉴 클릭시 해당 페이지에 메뉴 페이지가 나오게하는 예제 추가

project/ui/frontend/common/assets/css/abstracts/_variables.scss, project/ui/frontend/common/assets/css/components/_button.scss, project/ui/frontend/common/assets/css/main.scss, project/ui/frontend/common/assets/css/pages/_design-guide.scss, project/ui/frontend/common/assets/images/icon/chevron-left-medium.svg, project/ui/frontend/common/assets/images/icon/chevron-right-medium.svg, project/ui/frontend/common/nuxt.config.ts, project/ui/frontend/common/package.json, project/ui/frontend/common/pages/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-444
- https://mobigen.atlassian.net/browse/FAB2023-586
=> [FAB2023-444] feat: Button UI 퍼블리싱 

project/ui/frontend/common/assets/css/abstracts/_box-shadow.scss, project/ui/frontend/common/assets/css/base/_classes.scss, project/ui/frontend/common/assets/css/components/_checkbox.scss, project/ui/frontend/common/assets/css/components/_input.scss, project/ui/frontend/common/assets/css/components/_radio.scss, project/ui/frontend/common/assets/css/components/_switch.scss, project/ui/frontend/common/assets/css/main.scss, project/ui/frontend/common/assets/css/tailwind/_tailwind-base.scss, project/ui/frontend/common/pages/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-594
- https://mobigen.atlassian.net/browse/FAB2023-591
=> [FAB2023-594] feat: checkbox / input 퍼블리싱 

project/ui/frontend/common/assets/css/components/_button.scss, project/ui/frontend/common/assets/css/components/_radio.scss, project/ui/frontend/common/assets/css/main.scss, project/ui/frontend/common/components/extends/notification/Notification.scss, project/ui/frontend/common/components/extends/pagination/Pagination.scss, project/ui/frontend/common/components/extends/pagination/Pagination.vue, project/ui/frontend/common/pages/index.vue
https://mobigen.atlassian.net/browse/FAB2023-594
https://mobigen.atlassian.net/browse/FAB2023-636
=> [FAB2023-594] feat: Pagination UI 퍼블리싱

project/ui/frontend/common/components/extends/common/interfaces/events/Navigation.interface.ts, project/ui/frontend/common/components/extends/common/interfaces/functions/Navigation.interface.ts, project/ui/frontend/common/components/extends/common/interfaces/props/Navigation.interface.ts, project/ui/frontend/common/components/extends/tab/Tab.vue, project/ui/frontend/common/components/extends/tab/TabComposition.ts, project/ui/frontend/common/components/extends/tab/TabProps.ts
- [FAB2023-600](https://mobigen.atlassian.net/browse/FAB2023-600)
- [FAB2023-505](https://mobigen.atlassian.net/browse/FAB2023-505)
- [FAB2023-642](https://mobigen.atlassian.net/browse/FAB2023-642)
- Tab 컴포넌트 개발
- Tab 컴포넌트 상속 구조로 변경
[FAB2023-600]: https://mobigen.atlassian.net/browse/FAB2023-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-505]: https://mobigen.atlassian.net/browse/FAB2023-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-642]: https://mobigen.atlassian.net/browse/FAB2023-642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-600] Tab 컴포넌트 구조화 작업

project/ui/frontend/common/assets/css/abstracts/_variables.scss, project/ui/frontend/common/assets/css/components/_tag.scss, project/ui/frontend/common/assets/css/main.scss, project/ui/frontend/common/assets/images/icon/slash.svg, project/ui/frontend/common/components/base/breadcrumb/Breadcrumb.scss, project/ui/frontend/common/components/base/breadcrumb/Breadcrumb.vue, project/ui/frontend/common/pages/index.vue
> task
https://mobigen.atlassian.net/browse/FAB2023-592
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-592] tag, breadcrumb 컴포넌트 퍼블리싱

project/ui/frontend/common/components/extends/common/interfaces/events/Navigation.interface.ts, project/ui/frontend/common/components/extends/step/ComparisonOperator.ts, project/ui/frontend/common/components/extends/step/Step.vue, project/ui/frontend/common/components/extends/step/StepComposition.ts, project/ui/frontend/common/components/extends/step/StepProps.ts, project/ui/frontend/common/components/extends/tab/TabComposition.ts, project/ui/frontend/common/pages/components/navigation/index.vue
- [FAB2023-601](https://mobigen.atlassian.net/browse/FAB2023-601)
- [FAB2023-618](https://mobigen.atlassian.net/browse/FAB2023-618)
- [FAB2023-643](https://mobigen.atlassian.net/browse/FAB2023-643)
[FAB2023-601]: https://mobigen.atlassian.net/browse/FAB2023-601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-618]: https://mobigen.atlassian.net/browse/FAB2023-618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-643]: https://mobigen.atlassian.net/browse/FAB2023-643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-601] feat: Step Component 구조화 작업

project/ui/frontend/common/components/extends/common/interfaces/events/Select.interface.ts, project/ui/frontend/common/components/extends/common/interfaces/functions/Select.interface.ts, project/ui/frontend/common/components/extends/common/interfaces/props/Select.interface.ts, project/ui/frontend/common/components/extends/select-box/SelectBox.vue, project/ui/frontend/common/components/extends/select-box/SelectBoxComposition.ts, project/ui/frontend/common/components/extends/select-box/SelectBoxProps.ts, project/ui/frontend/common/package.json
- [FAB2023-602](https://mobigen.atlassian.net/browse/FAB2023-602)
- [FAB2023-507](https://mobigen.atlassian.net/browse/FAB2023-507)
- [FAB2023-641](https://mobigen.atlassian.net/browse/FAB2023-641)
- [FAB2023-651](https://mobigen.atlassian.net/browse/FAB2023-651)
- select box 컴포넌트 개발
- select box 컴포넌트 상속 구조로 변경
- @Kimjihyehee  코드 수정하기 전 버전이라 코드 수정한 내용이 포함되어야 함
[FAB2023-602]: https://mobigen.atlassian.net/browse/FAB2023-602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-507]: https://mobigen.atlassian.net/browse/FAB2023-507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-641]: https://mobigen.atlassian.net/browse/FAB2023-641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
=> [FAB2023-602] selectbox 컴포넌트 상속 구조로 변경

project/ui/frontend/common/components/extends/combo-box/ComboBox.vue, project/ui/frontend/common/components/extends/combo-box/ComboBoxComposition.ts, project/ui/frontend/common/components/extends/combo-box/ComboBoxProps.ts, project/ui/frontend/common/components/extends/common/interfaces/events/Select.interface.ts, project/ui/frontend/common/components/extends/common/interfaces/functions/Select.interface.ts, project/ui/frontend/common/components/extends/common/interfaces/props/Select.interface.ts, project/ui/frontend/common/components/extends/select-box/SelectBox.vue, project/ui/frontend/common/components/extends/select-box/SelectBoxComposition.ts, project/ui/frontend/common/components/extends/select-box/SelectBoxProps.ts, project/ui/frontend/common/package.json, project/ui/frontend/common/pages/combobox/index.vue
- [FAB2023-603](https://mobigen.atlassian.net/browse/FAB2023-603)
- [FAB2023-637](https://mobigen.atlassian.net/browse/FAB2023-637)
- 인터페이스 props 'isFirstSelectedEvent' 추가
- combo box 컴포넌트 상속 구조로 변경
- disable처리
[FAB2023-603]: https://mobigen.atlassian.net/browse/FAB2023-603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-637]: https://mobigen.atlassian.net/browse/FAB2023-637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-603] combobox 컴포넌트 상속 구조로 변경

project/ui/frontend/common/assets/css/components/_form.scss, project/ui/frontend/common/assets/css/components/_table.scss, project/ui/frontend/common/assets/css/components/_text-input.scss, project/ui/frontend/common/assets/css/components/_textarea.scss, project/ui/frontend/common/assets/css/main.scss, project/ui/frontend/common/components/extends/inline-notification/InlineNotification.scss, project/ui/frontend/common/pages/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-596
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB-2023-596] 공통 UI 퍼블리싱/ Table, Form

project/ui/frontend/common/assets/css/abstracts/_box-shadow.scss, project/ui/frontend/common/assets/css/abstracts/_fonts.scss, project/ui/frontend/common/assets/css/abstracts/_z-index.scss, project/ui/frontend/common/assets/css/components/_button-group.scss, project/ui/frontend/common/assets/css/components/_button.scss, project/ui/frontend/common/assets/css/components/_checkbox.scss, project/ui/frontend/common/assets/css/components/_input.scss, project/ui/frontend/common/assets/css/components/_modal.scss, project/ui/frontend/common/assets/css/components/_switch.scss, project/ui/frontend/common/assets/css/components/_text-input.scss, project/ui/frontend/common/assets/css/components/_textarea.scss, project/ui/frontend/common/assets/css/main.scss, project/ui/frontend/common/assets/css/pages/_design-guide.scss, project/ui/frontend/common/assets/css/tailwind/_tailwind-base.scss, project/ui/frontend/common/components/base/alert/alert.scss, project/ui/frontend/common/components/base/alert/alert.vue, project/ui/frontend/common/components/extends/inline-notification/InlineNotification.scss, project/ui/frontend/common/components/extends/notification/Notification.scss, project/ui/frontend/common/pages/index.vue, project/ui/frontend/common/pages/vue-final-modal/ModalConfirmPlainCss.vue, project/ui/frontend/common/pages/vue-final-modal/index.vue
- Task
https://mobigen.atlassian.net/browse/FAB2023-589
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-589] 공통 UI 퍼블리싱 - Modal, Alert Modal

project/ui/frontend/common/components/base/alert/alert.vue
https://mobigen.atlassian.net/browse/FAB2023-594
https://mobigen.atlassian.net/browse/FAB2023-598
=> [FAB2023-594] refactor: alert 내 notification 클래스 수정

project/ui/frontend/common/pages/index.vue
[- [이슈번호](이슈링크)](https://mobigen.atlassian.net/browse/FAB2023-381)
https://mobigen.atlassian.net/browse/FAB2023-678
=> [FAB2023-381] feat: 개발 UI 확인할 수 있도록 변경

project/ui/frontend/common/assets/css/abstracts/_fonts.scss, project/ui/frontend/common/assets/css/components/_badge.scss, project/ui/frontend/common/assets/css/components/_button-group.scss, project/ui/frontend/common/assets/css/components/_button.scss, project/ui/frontend/common/assets/css/components/_form.scss, project/ui/frontend/common/assets/css/components/_input.scss, project/ui/frontend/common/assets/css/components/_modal.scss, project/ui/frontend/common/assets/css/components/_notification.scss, project/ui/frontend/common/assets/css/components/_switch.scss, project/ui/frontend/common/assets/css/components/_tag.scss, project/ui/frontend/common/assets/css/components/_text-input.scss, project/ui/frontend/common/assets/css/components/_toggle.scss, project/ui/frontend/common/assets/css/pages/_design-guide.scss, project/ui/frontend/common/components/base/alert/alert.scss, project/ui/frontend/common/components/base/alert/alert.vue, project/ui/frontend/common/components/base/breadcrumb/Breadcrumb.scss, project/ui/frontend/common/pages/index.vue
https://mobigen.atlassian.net/browse/FAB2023-677
=> [FAB2023-677] font 믹스인 수정 및 정리, alert 스타일 삭제

project/ui/frontend/common/assets/css/main.scss, project/ui/frontend/common/components/extends/tab/Tab.vue, project/ui/frontend/common/components/extends/tab/tab.scss, project/ui/frontend/common/pages/components/navigation/index.vue
https://mobigen.atlassian.net/browse/FAB2023-597
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-597] tab 퍼블리싱

project/ui/frontend/common/components/extends/tab/tab.scss, project/ui/frontend/common/pages/components/navigation/index.vue
https://mobigen.atlassian.net/browse/FAB2023-746
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-746] Tab 유형 추가 퍼블리싱

project/ui/frontend/data-fabric/nuxt.config.ts, project/ui/frontend/data-fabric/package.json
https://mobigen.atlassian.net/browse/FAB2023-817
https://mobigen.atlassian.net/browse/FAB2023-819
- sass 설치
=> [FAB2023-819] feat: data-fabric sass 설치

project/ui/frontend/data-fabric/nuxt.config.ts, project/ui/frontend/data-fabric/package.json
https://mobigen.atlassian.net/browse/FAB2023-819
https://mobigen.atlassian.net/browse/FAB2023-817
- svg 아이콘 실행 
- 크로스브라우징 적용
=> [FAB2023-817] feat: data-fabric svg 아이콘 세팅, 크로스브라우징 적용 

project/ovp/frontend/common/nuxt.config.ts, project/ovp/frontend/common/package-lock.json, project/ovp/frontend/common/package.json, project/ovp/frontend/common/store/sample.ts, project/ovp/frontend/ovp/nuxt.config.ts, project/ovp/frontend/ovp/store/sample.ts
- [FAB2023-867](https://mobigen.atlassian.net/browse/FAB2023-867)
- Pinia 설정
- UI 빌드 수정
[FAB2023-867]: https://mobigen.atlassian.net/browse/FAB2023-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-843] UI 설정

project/ovp/frontend/common/eslint.config.js, project/ovp/frontend/common/package-lock.json, project/ovp/frontend/common/package.json, project/ovp/frontend/ovp/eslint.config.js, project/ovp/frontend/ovp/package-lock.json, project/ovp/frontend/ovp/package.json
[FAB2023-843](https://mobigen.atlassian.net/browse/FAB2023-843)
* [FAB2023-769](https://mobigen.atlassian.net/browse/FAB2023-769)
[FAB2023-843]: https://mobigen.atlassian.net/browse/FAB2023-843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-769]: https://mobigen.atlassian.net/browse/FAB2023-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-843] feat: ESLint 설정 추가

project/ovp/frontend/common/components/extends/tab/Tab.vue, project/ovp/frontend/ovp/components/search/common/custom-knowledge-graph.vue, project/ovp/frontend/ovp/components/search/common/resource-box.vue, project/ovp/frontend/ovp/components/search/detail-tab/default-info.vue, project/ovp/frontend/ovp/components/search/detail-tab/knowledge-graph.vue, project/ovp/frontend/ovp/components/search/detail-tab/lineage.vue, project/ovp/frontend/ovp/components/search/detail-tab/profiling.vue, project/ovp/frontend/ovp/components/search/detail-tab/query.vue, project/ovp/frontend/ovp/components/search/detail-tab/recommend-model.vue, project/ovp/frontend/ovp/components/search/detail-tab/sample.vue, project/ovp/frontend/ovp/components/search/detail-tab/schema.vue, project/ovp/frontend/ovp/components/search/filter-item.vue, project/ovp/frontend/ovp/components/search/lineage-graph.vue, project/ovp/frontend/ovp/components/search/preview.vue, project/ovp/frontend/ovp/components/search/resource-box-list.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue, project/ovp/frontend/ovp/pages/portal/search/index.vue
https://mobigen.atlassian.net/browse/FAB2023-898
https://mobigen.atlassian.net/browse/FAB2023-899
- 컴포넌트 구조대로 초기 파일 생성
=> [FAB2023-898] feat: 컴포넌트 구조대로 초기 파일 생성

project/ovp/frontend/ovp/pages/index.vue, project/ovp/frontend/ovp/plugins/custom-fetch-api.ts, project/ovp/server/src/main/resources/application.yml
- [FAB2023-905](https://mobigen.atlassian.net/browse/FAB2023-905)
- OVP에 API 연동 모듈 추가
- 샘플 코드 추가
[FAB2023-905]: https://mobigen.atlassian.net/browse/FAB2023-905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-898] API 모듈 개발

project/ovp/frontend/ovp/components/search/common/resource-box.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue
- [FAB2023-914](https://mobigen.atlassian.net/browse/FAB2023-914)
- [FAB2023-914](https://mobigen.atlassian.net/browse/FAB2023-914)
- 데이터 모델 상세 공통화면  UI 화면 구성
[FAB2023-914]: https://mobigen.atlassian.net/browse/FAB2023-914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-914]: https://mobigen.atlassian.net/browse/FAB2023-914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-914] feat: OVP/탐색화면- 데이터모델 상세 공통 화면 개발

project/ovp/frontend/ovp/components/search/detail-default.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue
- [FAB2023-914](https://mobigen.atlassian.net/browse/FAB2023-914)
- [FAB2023-914](https://mobigen.atlassian.net/browse/FAB2023-914)
-  - resource-box컴포넌트내 불필요한 부분 제외 및 detail-default컴포넌트추가
[FAB2023-914]: https://mobigen.atlassian.net/browse/FAB2023-914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-914]: https://mobigen.atlassian.net/browse/FAB2023-914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-914] feat: OVP/탐색상세화면수정

project/ovp/frontend/common/components/extends/step/Step.vue, project/ovp/frontend/common/components/extends/step/StepComposition.ts, project/ovp/frontend/common/components/extends/tab/TabComposition.ts
- [FAB2023-928](https://mobigen.atlassian.net/browse/FAB2023-928)
=> [FAB2023-898] fix: tab에서 현재탭 선택 안되는 문제 수정 및 tab, step 오버라이딩안된 함수 추가

project/ovp/frontend/common/components/extends/grid/Grid.vue
- [FAB2023-928](https://mobigen.atlassian.net/browse/FAB2023-928)
=> [FAB2023-898] fix: ovp 화면에서 ag-grid 사용시 에러가 발생하는 문제 수정

project/ovp/frontend/ovp/components/search/detail-tab/sample.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue
- [FAB2023-928](https://mobigen.atlassian.net/browse/FAB2023-928)
=> [FAB2023-898] 탐색 / 상세 샘플탭에 ag-grid 추가

project/ovp/frontend/common/nuxt.config.ts, project/ovp/frontend/common/package-lock.json, project/ovp/frontend/common/package.json, project/ovp/frontend/common/pages/code-mirror/index.vue, project/ovp/frontend/common/plugins/code-mirror.ts
- [FAB2023-928](https://mobigen.atlassian.net/browse/FAB2023-928)
=> [FAB2023-898] common / code-mirror 모듈 및 플러그인 추가

project/ovp/frontend/ovp/nuxt.config.ts, project/ovp/frontend/ovp/package-lock.json, project/ovp/frontend/ovp/package.json
[FAB2023-898](https://mobigen.atlassian.net/browse/FAB2023-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) https://mobigen.atlassian.net/browse/FAB2023-898
[FAB2023-628](https://mobigen.atlassian.net/browse/FAB2023-628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) https://mobigen.atlassian.net/browse/FAB2023-628
- /ovp 이하 페이지에서 ag-grid 표시 안됨 수정
[FAB2023-628]: https://mobigen.atlassian.net/browse/FAB2023-628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-898] ag-grid /ovp 화면 표시 오류 수정

project/ovp/frontend/ovp/components/search/preview.vue
https://mobigen.atlassian.net/browse/FAB2023-911
https://mobigen.atlassian.net/browse/FAB2023-898
=> [FAB2023-898] preview - 컴포넌트 props 추가, 데이터 전송 방식 computed 으로 변경

project/ovp/frontend/ovp/components/search/preview.vue
https://mobigen.atlassian.net/browse/FAB2023-911
https://mobigen.atlassian.net/browse/FAB2023-898
=> [FAB2023-898] preview - 변수명 수정하면서 닫기 버튼 상태값 반대로 수정

project/ovp/frontend/ovp/layouts/default.vue, project/ovp/frontend/ovp/layouts/login.vue, project/ovp/frontend/ovp/middleware/layout.global.ts, project/ovp/frontend/ovp/pages/portal/search/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-939
- 공통 layout 처리
=> [FAB2023-898] 공통 layout 처리

project/ovp/frontend/common/assets/css/components/_menu.scss, project/ovp/frontend/common/components/extends/select-box/select.scss
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-832] select z-index 조정

project/ovp/frontend/ovp/assets/css/component/_resource-box.scss, project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/pages/_pub/login/pw-find/index.vue, project/ovp/frontend/ovp/pages/_pub/login/pw-reset/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-788
- https://mobigen.atlassian.net/browse/FAB2023-941
=> [FAB2023-788] 비밀번호 재 설정, 비밀번호 찾기 - 퍼블리싱

project/ovp/frontend/common/components/extends/select-box/select.scss
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-832] select > menu-search 너비 추가

project/ovp/frontend/common/assets/css/components/common/_input.scss, project/ovp/frontend/common/assets/css/components/common/_list.scss, project/ovp/frontend/common/components/extends/menu-seach/menu-search.vue, project/ovp/frontend/common/components/extends/select-box/SelectBox.vue, project/ovp/frontend/common/pages/design-guide/pages/guide-checkbox.vue, project/ovp/frontend/common/pages/design-guide/pages/guide-dropdown.vue, project/ovp/frontend/common/pages/design-guide/pages/guide-form.vue, project/ovp/frontend/common/pages/design-guide/pages/guide-menu.vue, project/ovp/frontend/common/pages/design-guide/pages/guide-modal.vue, project/ovp/frontend/ovp/components/common/resource-box/resource-box-list.vue, project/ovp/frontend/ovp/pages/_pub/search-detail/index.vue, project/ovp/frontend/ovp/pages/_pub/search/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-906
=> [FAB2023-898] checkbox, list - 말줄임 스타일 추가

project/ovp/frontend/ovp/pages/_pub/search-detail/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-877
- https://mobigen.atlassian.net/browse/FAB2023-789
=> [FAB2023-789] feat: 데이터 모델 상세 - 삭제 버튼 추가

project/ovp/frontend/ovp/components/search/detail-default.vue, project/ovp/frontend/ovp/components/search/detail-tab/default-info.vue, project/ovp/frontend/ovp/components/search/detail-tab/knowledge-graph.vue, project/ovp/frontend/ovp/components/search/detail-tab/query.vue, project/ovp/frontend/ovp/components/search/detail-tab/recommend-model.vue, project/ovp/frontend/ovp/components/search/detail-tab/sample.vue, project/ovp/frontend/ovp/components/search/detail-tab/schema.vue, project/ovp/frontend/ovp/layouts/header.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue
* [FAB2023-928](https://mobigen.atlassian.net/browse/FAB2023-928)
=> [FAB2023-898] 탐색 퍼블리싱 적용

project/ovp/frontend/common/components/extends/menu-seach/button/menu-search-button.vue, project/ovp/frontend/common/components/extends/menu-seach/menu-search.vue
- [FAB2023-906](https://mobigen.atlassian.net/browse/FAB2023-906)
- OVP 폴더에서 컴포넌트 사용시 경로 및 컴포넌트생성 오류 발생 해결
[FAB2023-906]: https://mobigen.atlassian.net/browse/FAB2023-906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Menu-search 경로명 오류 수정

project/ovp/frontend/ovp/components/search/detail-tab/schema.vue
- [FAB2023-920](https://mobigen.atlassian.net/browse/FAB2023-920)
[FAB2023-920]: https://mobigen.atlassian.net/browse/FAB2023-920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-920] feat: 데이터 모델 상세 - 스키마 탭 개발

project/ovp/frontend/ovp/assets/css/component/_resource-box.scss, project/ovp/frontend/ovp/components/common/resource-box/resource-box-edit-part.vue, project/ovp/frontend/ovp/components/common/resource-box/resource-box-props.ts, project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-902
- 수정 퍼블 적용
- preview 기능 관련 class 처리 추가
=> [FAB2023-898] resource-box 컴포넌트 수정 퍼블 적용 외

project/ovp/frontend/common/assets/css/components/_button.scss, project/ovp/frontend/ovp/assets/css/component/_common.scss, project/ovp/frontend/ovp/assets/css/layouts/_common.scss, project/ovp/frontend/ovp/assets/css/main.scss, project/ovp/frontend/ovp/assets/css/pages/_editable-group.scss, project/ovp/frontend/ovp/assets/css/pages/_search.scss, project/ovp/frontend/ovp/pages/_pub/govern/category/index.vue, project/ovp/frontend/ovp/pages/_pub/govern/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-870] 거버넌스 - 카테고리

project/ovp/frontend/ovp/assets/css/layouts/_common.scss, project/ovp/frontend/ovp/pages/_pub/govern/category/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-870] 카테고리 데이터 박스 스크롤 문제 수정

project/ovp/frontend/ovp/components/search/detail-tab/profiling.vue
- [FAB2023-913](https://mobigen.atlassian.net/browse/FAB2023-913)
[FAB2023-913]: https://mobigen.atlassian.net/browse/FAB2023-913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-913] feat: 데이터 모델 상세 - 프로파일링 탭 개발

project/ovp/frontend/common/components/extends/menu-seach/MenuSearchComposition.ts, project/ovp/frontend/common/components/extends/menu-seach/button/MenuSearchButtonComposition.ts, project/ovp/frontend/common/pages/menu-search/index.vue
- 선택리스트 상위 컴포넌트에서 값 변경 가능하도록 수정
=> menu-search 선택리스트 상위 컴포넌트에서 값 변경 가능하도록 수정

project/ovp/frontend/ovp/components/search/detail-tab/default-info.vue
- [FAB2023-919](https://mobigen.atlassian.net/browse/FAB2023-919)
[FAB2023-919]: https://mobigen.atlassian.net/browse/FAB2023-919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-919] feat: 데이터 모델 상세 - 기본 정보 탭 개발

project/ovp/frontend/common/pages/menu-search/index.vue
=> 병합으로 인한 menu-search 오류 수정

project/ovp/frontend/common/assets/css/components/_table.scss, project/ovp/frontend/common/components/extends/tab/tab.scss, project/ovp/frontend/ovp/assets/css/layouts/_common.scss, project/ovp/frontend/ovp/assets/images/icon/report-tag.svg, project/ovp/frontend/ovp/pages/_pub/govern/category/index.vue, project/ovp/frontend/ovp/pages/_pub/govern/glossary/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-862] 거버넌스 - 용어사전 퍼블리싱

project/ovp/frontend/ovp/components/search/data-filter.vue, project/ovp/frontend/ovp/nuxt.config.ts, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/frontend/ovp/store/search/common.ts, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search/client/SearchClient.java
- https://mobigen.atlassian.net/browse/FAB2023-903
- https://mobigen.atlassian.net/browse/FAB2023-956
=> [FAB2023-898] 탐색 목록, 필터 목록 조회 backend 처리 추가

project/ovp/server/src/main/resources/application.yml
- https://mobigen.atlassian.net/browse/FAB2023-903
- https://mobigen.atlassian.net/browse/FAB2023-956
=> [FAB2023-898] 데이터 탐색 - 목록 조회 관련 api 오류 수정

project/ovp/frontend/common/components/base/breadcrumb/Breadcrumb.scss, project/ovp/frontend/ovp/assets/css/component/_menu-data.scss, project/ovp/frontend/ovp/assets/css/main.scss, project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/pages/_pub/creation/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-790] 데이터모델 생성 화면 추가 수정

project/ovp/frontend/ovp/components/search/data-filter.vue, project/ovp/frontend/ovp/store/search/common.ts
- https://mobigen.atlassian.net/browse/FAB2023-960
- https://mobigen.atlassian.net/browse/FAB2023-904
=> [FAB2023-898]  필터 변경된 규칙에 맞춰 데이터 저장 방식 변경

project/ovp/frontend/common/components/extends/menu-seach/button/MenuSearchButtonComposition.ts, project/ovp/frontend/common/components/extends/menu-seach/button/menu-search-button.vue, project/ovp/frontend/common/pages/menu-search/index.vue
- menu-search-button 컴포넌트 클릭 이벤트 추가
=> [FAB2023-898] feat: menu-search-button 클릭 이벤트 추가

project/ovp/frontend/ovp/components/common/resource-box/resource-box-edit-part.vue, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/frontend/ovp/pages/portal/search/top-bar.vue, project/ovp/frontend/ovp/store/search/common.ts, project/ovp/frontend/ovp/utils/intersection-observer.ts, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchService.java
- https://mobigen.atlassian.net/browse/FAB2023-903
- 목록 조회 화면 구현
- data filter 및 sort option 목록 조회 쿼리에 반영 완료
- 초기화 버튼 구현 완료
- resource-box 데이터 처리 구현 완료
- 정형/비정형 데이터 표시 구현 완료
=> [FAB2023-898] feat : 데이터 탐색 - 목록 구현 (쿼리 반영)

project/ovp/frontend/ovp/plugins/custom-fetch-api.ts
- [FAB2023-900](https://mobigen.atlassian.net/browse/FAB2023-900)
- custom-fetch 데이터 변환 및 에러 얼럿 삭제
[FAB2023-900]: https://mobigen.atlassian.net/browse/FAB2023-900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-900] custom-fetch 데이터 변환 및 에러 얼럿 삭제

project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/TablesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/Columns.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/Owner.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/Profile.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/ProfileColumn.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/Sample.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/SampleData.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/TableProfile.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/Tables.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/Votes.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/response/DataModelSampleDataResponse.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/response/DataModelSchemaResponse.java
- [FAB2023-931](https://mobigen.atlassian.net/browse/FAB2023-931)
=> [FAB2023-898] 데이터 모델 상세, 스키마, 샘플 데이터, 프로파일링 API 추가

project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/ProfileColumn.java
- [FAB2023-931](https://mobigen.atlassian.net/browse/FAB2023-931)
[FAB2023-931]: https://mobigen.atlassian.net/browse/FAB2023-931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-898] ProfileColumn 중복 변수 버그 수정

project/ovp/frontend/ovp/assets/css/layouts/_common.scss
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-788] l-split 공통 레이아웃 수정

project/ovp/frontend/ovp/pages/_pub/govern/category/index.vue, project/ovp/frontend/ovp/pages/_pub/govern/glossary/index.vue, project/ovp/frontend/ovp/pages/_pub/govern/tags/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-973
- https://mobigen.atlassian.net/browse/FAB2023-791
- 카테고리&용어&용어사전&분류 추가 모달 - 퍼블리싱
=> [FAB2023-791] 카테고리&용어&용어사전&분류 추가 모달 - 퍼블리싱

project/ovp/frontend/common/assets/css/base.scss, project/ovp/frontend/common/components/base/loading/Loading.scss, project/ovp/frontend/common/components/base/loading/Loading.vue, project/ovp/frontend/common/pages/design-guide/layouts/guide-main.vue, project/ovp/frontend/common/pages/design-guide/pages/guide-loading.vue
- https://mobigen.atlassian.net/browse/FAB2023-595
=> [FAB2024-595] 공통 Ui 퍼블리싱 - loading

project/ovp/frontend/common/assets/css/components/_modal.scss, project/ovp/frontend/ovp/assets/css/layouts/_header.scss, project/ovp/frontend/ovp/assets/css/main.scss, project/ovp/frontend/ovp/assets/css/pages/_my-page.scss, project/ovp/frontend/ovp/pages/_pub/creation/index.vue, project/ovp/frontend/ovp/pages/_pub/my-page/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-788] 마이페이지 화면 퍼블리싱

project/ovp/server/pom.xml, project/ovp/server/src/main/java/com/mobigen/framework/configuration/DatabaseConfiguration.java, project/ovp/server/src/main/java/com/mobigen/framework/security/LocalLoginFilter.java, project/ovp/server/src/main/java/com/mobigen/ovp/OvpApplication.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthController.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthService.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/CommonController.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/CommonService.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserController.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserRoleService.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserService.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/entity/UserEntity.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/entity/UserRole.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/entity/UserRoleEntity.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/repository/UserRepository.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/repository/UserRoleRepository.java, project/ovp/server/src/main/resources/application.yml
- [FAB2023-949)](https://mobigen.atlassian.net/browse/FAB2023-949)
- 회원 가입 API 개발
- 사용자 동기화 API 개발
- IWDF JPA 설정 오류 해결
- DB 설정
=> [FAB2023-949] 회원 가입 API 개발

project/ovp/frontend/ovp/components/search/detail-default.vue
- [FAB2023-915](https://mobigen.atlassian.net/browse/FAB2023-915)
[FAB2023-915]: https://mobigen.atlassian.net/browse/FAB2023-915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-915] feat: 추천/비추천/북마크/링크 기능 개발

project/ovp/frontend/common/components/extends/menu-seach/MenuSearchComposition.ts, project/ovp/frontend/common/components/extends/menu-seach/MenuSearchProps.ts, project/ovp/frontend/common/components/extends/menu-seach/button/menu-search-button.vue, project/ovp/frontend/common/components/extends/menu-seach/menu-search.vue
- 초기화 기능 변경 (원본 데이터로 초기화 -> Clear ALL 로 변경)
- 기획 요청사항 수정(선택 갯수 뱃지가 1개 이상 일때만 보이게 변경)
=> [FAB2023-898] feat: 초기화 기능 변경, 기획 요청사항 수정

project/ovp/frontend/ovp/store/search/common.ts
- https://mobigen.atlassian.net/browse/FAB2023-956
- filter 단건 조회 가라데이터 이용 front 부분만 구현 (추후 API 구현 후 수정 필요)
=> [FAB2023-898] filter 단건 조회 front 부분 구현

project/ovp/server/src/main/java/com/mobigen/framework/configuration/WebSecurityConfiguration.java, project/ovp/server/src/main/java/com/mobigen/framework/result/JsonResult.java, project/ovp/server/src/main/java/com/mobigen/framework/security/JwtFilter.java, project/ovp/server/src/main/java/com/mobigen/framework/security/LocalLoginFilter.java, project/ovp/server/src/main/java/com/mobigen/framework/utility/Token.java, project/ovp/server/src/main/java/com/mobigen/framework/utility/User.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserController.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserService.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/dto/UserInfoDTO.java, project/ovp/server/src/main/resources/application.yml
- Feature (기능 추가)
- 토큰 검증 기능 추가
- 로컬 로그인 - 토큰 검증/재발급 로직 추가
- 서버 접근 시 401 이슈 해결
- 사용자 정보 출력 API 개발
=> [FAB2023-949] 사용자 정보 출력 API 개발 및 기타 서버 수정

project/ovp/frontend/common/components/extends/editable-group/EditableGroup.vue, project/ovp/frontend/common/components/extends/editable-group/EditableGroupProps.ts, project/ovp/frontend/common/pages/editable-group/index.vue, project/ovp/frontend/common/pages/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-1015
- EditableGroup 컴포넌트 개발
=> [FAB2023-898] EditableGroup 컴포넌트 개발

project/ovp/frontend/ovp/components/common/resource-box/resource-box-list.vue, project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/frontend/ovp/store/search/common.ts
- https://mobigen.atlassian.net/browse/FAB2023-1047
- 데이터모델 미리보기 컴포넌트 - 탐색 목록 API fqn 추가
=> [FAB2023-898] 데이터모델 미리보기 컴포넌트 - 탐색 목록 API fqn 추가

project/ovp/frontend/common/assets/css/components/_form.scss, project/ovp/frontend/common/assets/css/components/_switch.scss, project/ovp/frontend/common/components/extends/datepicker/Datepicker.scss, project/ovp/frontend/ovp/pages/_pub/admin/service/index.vue
=> [FAB2023-971] 관리/ 메타 데이터, 프로파일러 수집 추가 모달 - 퍼블리싱

project/ovp/frontend/common/components/extends/editable-group/EditableGroup.vue, project/ovp/frontend/common/components/extends/editable-group/EditableGroupProps.ts, project/ovp/frontend/common/pages/editable-group/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-1015
- 사용하지 않는 props 제거
- cancel 이벤트 수정
=> [FAB2023-898] 사용하지 않는 props 제거, cancel 이벤트 수정

project/ovp/server/pom.xml, project/ovp/server/src/main/java/com/mobigen/framework/security/LocalLoginFilter.java, project/ovp/server/src/main/java/com/mobigen/framework/utility/Token.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthController.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthService.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/PwResetEntity.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/PwResetRepository.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/EmailUtil.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/OvpProperties.java, project/ovp/server/src/main/java/com/mobigen/ovp/email/EmailController.java, project/ovp/server/src/main/java/com/mobigen/ovp/email/EmailService.java, project/ovp/server/src/main/java/com/mobigen/ovp/email/EmailUtil.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/repository/UserRepository.java, project/ovp/server/src/main/resources/application.yml, project/ovp/server/src/main/resources/templates/ovp_pwReset.html
- 비밀번호 재설정 API 개발(고유링크, 메일전송, 마이페이지 API)
=> [FAB2023-949] 비밀번호 재설정 API 개발

project/ovp/frontend/common/assets/css/components/_modal.scss, project/ovp/frontend/common/assets/css/components/_radio.scss, project/ovp/frontend/common/assets/css/components/_table.scss, project/ovp/frontend/common/assets/css/components/common/_input-group.scss, project/ovp/frontend/ovp/pages/_pub/admin/user/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-885
=> [FAB2023-885] 관리/ 사용자 관리 - 퍼블리싱

project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/response/DataModelDetailResponse.java
* [FAB2023-1043](https://mobigen.atlassian.net/browse/FAB2023-1043)
[FAB2023-1043]: https://mobigen.atlassian.net/browse/FAB2023-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-898] 데이터모델 상세 depth 추가

project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthController.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthService.java, project/ovp/server/src/main/java/com/mobigen/ovp/email/EmailService.java
- Feature
- 고유링크 유효성 검증 API 추가
=> [FAB2023-949] 비밀번호 변경 API 수정

project/ovp/frontend/common/components/base/loading/Loading.vue, project/ovp/frontend/ovp/assets/css/layouts/_section.scss, project/ovp/frontend/ovp/pages/_pub/admin/overview/index.vue
_##_ 유형
- 페이지에서 공통으로 사용하는 탭 부분 스타일 일괄 수정
=> [FAB2023-898] feat: 화면 클래스, 스타일 수정 - 퍼블리싱 

project/ovp/server/src/main/java/com/mobigen/ovp/email/EmailService.java
- Task (기능 변경)
- Nuxt 동적 라우트 이슈로 인한 메일 리다이랙트 URL 쿼리 파라미터 형식으로 변경
=> [FAB2023-949] Nuxt 동적 라우트 이슈로 인한 메일 리다이랙트 URL 쿼리 파라미터 형식으로 변경

project/ovp/frontend/common/components/extends/menu-seach/MenuSearchComposition.ts, project/ovp/frontend/common/components/extends/menu-seach/MenuSearchProps.ts, project/ovp/frontend/common/components/extends/menu-seach/button/MenuSearchButtonComposition.ts, project/ovp/frontend/common/components/extends/menu-seach/button/menu-search-button.vue, project/ovp/frontend/common/components/extends/menu-seach/tag/MenuSearchTagComposition.ts, project/ovp/frontend/common/components/extends/menu-seach/tag/menu-search-tag.vue, project/ovp/frontend/common/components/extends/menu-seach/type/MenuSearchTypeComposition.ts, project/ovp/frontend/common/components/extends/menu-seach/type/MenuSearchTypeProps.ts, project/ovp/frontend/common/package-lock.json, project/ovp/frontend/common/package.json, project/ovp/frontend/common/pages/menu-search/index.vue
- menu-search isShow 중복 이슈 해결
- menu-search-tag 공통 컴포넌트 개발
=> [FAB2023-898] menu-search-tag 공통 컴포넌트 개발

project/ovp/frontend/ovp/store/search/common.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/SearchClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchService.java
- https://mobigen.atlassian.net/browse/FAB2023-1004
- 3개 탭 데이터 조회 하도록 수정 (테이블,스토리지,융합모델)
- 각 항목별 건수 조회하도록 수정
- 데이터 및 건수 처리하는 store 코드 수정
=> [FAB2023-898] 탐색 목록 조회 API 및 store 수정 (index 처리) 

project/ovp/frontend/common/components/base/accordion/accordion.scss, project/ovp/frontend/common/components/base/accordion/accordion.vue
https://mobigen.atlassian.net/browse/FAB2023-1050
=> [FAB2023-1050] 아코디언 트랜지션 효과 추가 - 퍼블리싱

project/ovp/frontend/ovp/components/login/pw-reset.vue, project/ovp/frontend/ovp/pages/portal/login/pw-reset/[uuid].vue, project/ovp/frontend/ovp/store/login/index.ts
- [FAB2023-948](https://mobigen.atlassian.net/browse/FAB2023-948)
- [FAB2023-953](https://mobigen.atlassian.net/browse/FAB2023-953)
- 서버 연동 처리
- 고유 링크 유효성 확인 추가
[FAB2023-948]: https://mobigen.atlassian.net/browse/FAB2023-948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-953]: https://mobigen.atlassian.net/browse/FAB2023-953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-948] 비밀번호 재설정 화면 개발

project/ovp/server/src/main/java/com/mobigen/ovp/mypage/MyPageController.java, project/ovp/server/src/main/java/com/mobigen/ovp/mypage/MyPageService.java, project/ovp/server/src/main/java/com/mobigen/ovp/mypage/client/MyPageClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/mypage/dto/response/UserInfoResponse.java, project/ovp/server/src/main/java/com/mobigen/ovp/sample/client/SampleClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserService.java
- [FAB2023-989](https://mobigen.atlassian.net/browse/FAB2023-989)
- [FAB2023-1038](https://mobigen.atlassian.net/browse/FAB2023-1038)
- 사용자 정보 조회 API
- 사용자 정보(표시이름, 설명, 역할) 수정 API
- https://mobigen.atlassian.net/wiki/spaces/FAB2023/pages/1002602553/UI+-+API
[FAB2023-989]: https://mobigen.atlassian.net/browse/FAB2023-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-1038]: https://mobigen.atlassian.net/browse/FAB2023-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-989] 마이페이지 메인페이지 API 개발

project/ovp/frontend/ovp/composables/intersectionObserverHelper.ts, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/frontend/ovp/store/common/paging.ts, project/ovp/frontend/ovp/store/governance/Category/index.ts, project/ovp/frontend/ovp/store/search/common.ts, project/ovp/server/src/main/java/com/mobigen/ovp/category/CategoryController.java, project/ovp/server/src/main/java/com/mobigen/ovp/category/CategoryService.java, project/ovp/server/src/main/java/com/mobigen/ovp/category/dto/CategoryDTO.java, project/ovp/server/src/main/java/com/mobigen/ovp/category/entity/CategoryEntity.java, project/ovp/server/src/main/java/com/mobigen/ovp/category/entity/CategoryMatchEntity.java, project/ovp/server/src/main/java/com/mobigen/ovp/category/repository/CategoryMatchRepository.java, project/ovp/server/src/main/java/com/mobigen/ovp/category/repository/CategoryRepository.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/ModelConvertUtil.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/entity/ModelIndex.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/SearchClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchService.java
- https://mobigen.atlassian.net/browse/FAB2023-999 
- https://mobigen.atlassian.net/browse/FAB2023-1006
- 카테고리 API 구현
- 카테고리 tree 조회
- 카테고리 노드 별 model list 조회
- model list 조회 화면 infinite scroll 적용
- infinite scroll 모듈로 분리
- https://mobigen.atlassian.net/wiki/spaces/FAB2023/pages/1018954057/UI+infinite-scroll+intersectionObserverHelper
=> [FAB2023-999] 카테고리 API 1차 구현 외

project/ovp/frontend/ovp/components/common/resource-box/resource-box-common-props.ts, project/ovp/frontend/ovp/components/common/resource-box/resource-box-list-props.ts, project/ovp/frontend/ovp/components/common/resource-box/resource-box-list.vue, project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-1048
- resource-box-list 에 임의구현 했던 checkbox 코드를 resource-box 로 이동 (퍼블리싱)
=> [FAB2023-898] feat : resource-box-list checkbox 기능 수정

project/ovp/frontend/ovp/components/search/preview.vue, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/frontend/ovp/pages/portal/search/top-bar.vue, project/ovp/frontend/ovp/store/common/paging.ts, project/ovp/frontend/ovp/store/search/common.ts
- https://mobigen.atlassian.net/browse/FAB2023-1056
- 탐색 화면 탭 개발
=> [FAB2023-898] 탐색화면 탭 개발

project/ovp/frontend/common/components/extends/modal/Modal.vue, project/ovp/frontend/common/components/extends/modal/ModalComposition.ts, project/ovp/frontend/common/components/extends/modal/ModalProps.ts, project/ovp/frontend/common/pages/vue-final-modal/index.vue
=> feat: 모달 width, heigth 적용되게 코드 수정

project/ovp/frontend/common/assets/css/base.scss, project/ovp/frontend/common/assets/css/components/_modal.scss, project/ovp/frontend/common/assets/css/pages/_design-guide.scss, project/ovp/frontend/common/components/extends/tree/Tree.vue, project/ovp/frontend/common/components/extends/tree/tree.scss, project/ovp/frontend/common/pages/design-guide/layouts/guide-lnb.vue, project/ovp/frontend/common/pages/design-guide/pages/guide-color.vue, project/ovp/frontend/common/pages/tree/index.vue, project/ovp/frontend/ovp/assets/css/pages/_creation.scss, project/ovp/frontend/ovp/pages/_pub/govern/category/index.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-791] 트리 컴포넌트, 거버넌스/ 카테고리 변경 트리 모달 - 퍼블리싱

project/ovp/frontend/ovp/components/datamodel-creation/selected-model.vue, project/ovp/frontend/ovp/pages/portal/datamodel-creation/index.vue, project/ovp/frontend/ovp/store/datamodel-creation/index.ts
- Feature (개선)
- [FAB2023-926](https://mobigen.atlassian.net/browse/FAB2023-926)
- 공통 코드 정리
[FAB2023-926]: https://mobigen.atlassian.net/browse/FAB2023-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-926] 데이터 모델 생성 Store 정리

project/ovp/frontend/ovp/components/datamodel-creation/datamodel-sample.json, project/ovp/frontend/ovp/components/datamodel-creation/list/DataModelListComposition.ts, project/ovp/frontend/ovp/components/datamodel-creation/list/data-model-list.vue
- [FAB2023-926](https://mobigen.atlassian.net/browse/FAB2023-926)
- filter 컴포넌트 변경
- 결과 없음 noti 출력
[FAB2023-926]: https://mobigen.atlassian.net/browse/FAB2023-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-926] filter 컴포넌트 변경 및 결과 없을때 noti 출력

project/ovp/frontend/ovp/assets/css/pages/_submit-form.scss, project/ovp/frontend/ovp/components/login/login.vue, project/ovp/frontend/ovp/components/login/sign-up.vue, project/ovp/frontend/ovp/pages/_pub/login/index.vue, project/ovp/frontend/ovp/pages/_pub/login/join/index.vue, project/ovp/frontend/ovp/pages/_pub/login/pw-find/index.vue, project/ovp/frontend/ovp/pages/_pub/login/pw-reset/index.vue, project/ovp/frontend/ovp/pages/portal/login/pw-find/index.vue, project/ovp/frontend/ovp/pages/portal/login/pw-reset/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-788] 로그인 화면 디자인 수정 -퍼블리싱

project/ovp/server/src/main/java/com/mobigen/framework/configuration/WebSecurityConfiguration.java, project/ovp/server/src/main/java/com/mobigen/framework/security/JwtFilter.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthController.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthService.java
- Feature (기능 추가)
- 로그아웃 API 개발
=> [FAB2023-949] feat: 로그아웃 API 개발

project/ovp/frontend/ovp/layouts/header.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1129] 로고 재적용

project/ovp/server/src/main/java/com/mobigen/ovp/glossary/GlossaryController.java, project/ovp/server/src/main/java/com/mobigen/ovp/glossary/GlossaryService.java, project/ovp/server/src/main/java/com/mobigen/ovp/glossary/client/GlossaryClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/glossary/client/dto/TermDto.java
- [FAB2023-1027](https://mobigen.atlassian.net/browse/FAB2023-1027)
[FAB2023-1027]: https://mobigen.atlassian.net/browse/FAB2023-1027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1027] 용어 추가 API

project/ovp/frontend/common/components/extends/grid/Grid.vue, project/ovp/frontend/common/components/extends/grid/GridComposition.ts, project/ovp/frontend/common/pages/ag-grid/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-628
- columnDefs 를 변경 가능 하도록 수정.
=> [FAB2023-898] feat : 컬럼정보 변경시 grid 에 반영되도록 수정함.

project/ovp/frontend/common/components/extends/tree/TreeProps.ts, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/frontend/ovp/store/governance/Category/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/category/CategoryController.java, project/ovp/server/src/main/java/com/mobigen/ovp/category/CategoryService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchService.java
- https://mobigen.atlassian.net/browse/FAB2023-1019
- 
- modelList data 없는 경우 빈 값으로 전달
=> [FAB2023-999] 카테고리 메인 개발 - 충돌 병합 후 에러 수정

project/ovp/frontend/common/assets/css/components/_menu.scss, project/ovp/frontend/common/components/extends/tree/tree.scss
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1121] menu-searh의 tree 유형 추가 퍼블리싱

project/ovp/frontend/ovp/components/common/resource-box/resource-box-list-props.ts, project/ovp/frontend/ovp/components/common/resource-box/resource-box-list.vue, project/ovp/frontend/ovp/components/common/resource-box/resource-box-props.ts, project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/frontend/ovp/store/governance/Category/index.ts
=> [FAB2023-999] 카테고리 메인 페이지 기능 2차 개발

project/ovp/frontend/ovp/components/common/Loading.vue, project/ovp/frontend/ovp/composables/loadingHelper.ts, project/ovp/frontend/ovp/layouts/default.vue, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/frontend/ovp/plugins/custom-fetch-api.ts, project/ovp/frontend/ovp/plugins/loading.ts, project/ovp/frontend/ovp/store/search/common.ts
- https://mobigen.atlassian.net/browse/FAB2023-1044
- api 호출할때 loader 표시되도록 처리함. (각 페이지에서 Loading 구현 불필요)
- loader(spinner) 추가
- loader on/off 옵션 추가 (api 별)
=> [FAB2023-898] loader 구현

project/ovp/frontend/common/components/extends/menu-seach/tree/MenuSearchTreeProps.ts, project/ovp/frontend/common/components/extends/menu-seach/tree/contents/menu-search-tree-contents.vue, project/ovp/frontend/common/components/extends/menu-seach/tree/menu-search-tree.vue, project/ovp/frontend/common/components/extends/tree/tree.scss, project/ovp/frontend/ovp/components/search/data-filter.vue, project/ovp/frontend/ovp/store/search/common.ts, project/ovp/server/src/main/java/com/mobigen/ovp/category/CategoryService.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/SearchClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchService.java
- 탐색화면 filter 조회 코드 수정
- 탐색화면 카테고리 tree filter 붙임
- 탐색화면 카테고리 선택시 query 에 포함되도록 처리 추가
=> [FAB2023-898] 탐색 목록 화면 기능 추가 구현

project/ovp/server/src/main/java/com/mobigen/ovp/user/UserClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserService.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/dto/UserInfoDTO.java
- 사용자 정보 API > isAdmin 데이터 변경 버그 수정
=> [FAB2023-949] 사용자 정보 API > isAdmin 데이터 변경 버그 수정

project/ovp/frontend/ovp/composables/loadingHelper.ts
- https://mobigen.atlassian.net/browse/FAB2023-1044
- timeout 코드 삭제
=> [FAB2023-898] fix : 화면 에러 발생시 loader 사라지지 않는 오류 수정

project/ovp/frontend/common/components/extends/menu-seach/tree/menu-search-tree.vue, project/ovp/frontend/ovp/components/common/preview/preview.vue, project/ovp/frontend/ovp/components/search/data-filter.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchService.java
- Feature (개선)
- 카테고리 API호출 코드 수정 및 텍스트 수정
- 미리보기 패널에서 모델명 클릭시 상세 페이지로 이동하는 기능 추가
=> [FAB2023-898] 탐색 목록 미리보기 패널 클릭 이벤트 처리 외 1건

project/ovp/frontend/common/components/extends/modal/Modal.vue, project/ovp/frontend/common/components/extends/modal/ModalComposition.ts, project/ovp/frontend/common/components/extends/modal/ModalProps.ts
- footer 버튼 기능 개선
- close emit 기능 개선
=> feat: 모달 기능 개선

project/ovp/frontend/ovp/components/admin/service/collection.vue, project/ovp/frontend/ovp/components/admin/service/connection-info.vue, project/ovp/frontend/ovp/components/admin/service/modal/modal-collection.vue, project/ovp/frontend/ovp/components/admin/service/modal/modal-log.vue, project/ovp/frontend/ovp/components/admin/service/modal/modal-service.vue, project/ovp/frontend/ovp/components/admin/service/repository.vue, project/ovp/frontend/ovp/components/admin/service/service-info.vue, project/ovp/frontend/ovp/components/admin/service/service-list.vue, project/ovp/frontend/ovp/pages/portal/admin/service/index.vue, project/ovp/frontend/ovp/store/admin/service/index.ts, project/ovp/frontend/ovp/utils/constant.ts
- [FAB2023-1173](https://mobigen.atlassian.net/browse/FAB2023-1173)  
[FAB2023-1173]: https://mobigen.atlassian.net/browse/FAB2023-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1173] 서비스 관리 메인 페이지 컴포넌트 분리화

project/ovp/frontend/ovp/components/admin/service/service-info.vue, project/ovp/frontend/ovp/components/admin/service/service-list.vue, project/ovp/frontend/ovp/store/admin/service/index.ts, project/ovp/frontend/ovp/store/glossary/index.ts, project/ovp/frontend/ovp/type/service.ts, project/ovp/frontend/ovp/utils/constant.ts
- [FAB2023-1173](https://mobigen.atlassian.net/browse/FAB2023-1173)
[FAB2023-1173]: https://mobigen.atlassian.net/browse/FAB2023-1173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1173] feat: 서비스 관리 메인 페이지 개발

project/ovp/frontend/ovp/pages/portal/search/index.vue
- category/data-filter 가 추가되면서, 참조 꼬임으로 발생한 화면 오류 수정
=> [FAB2023-898] fix : 탐색 data-filter 참조 오류 수정

project/ovp/frontend/common/assets/css/utility.scss, project/ovp/frontend/common/assets/css/vendors/v-tooltip.scss, project/ovp/frontend/common/nuxt.config.ts, project/ovp/frontend/common/package.json, project/ovp/frontend/common/pages/design-guide/layouts/guide-lnb.vue, project/ovp/frontend/common/pages/design-guide/layouts/guide-main.vue, project/ovp/frontend/common/pages/design-guide/pages/guide-tooltip.vue, project/ovp/frontend/common/plugins/vue3-tooltip.ts, project/ovp/frontend/ovp/nuxt.config.ts, project/ovp/frontend/ovp/package.json, project/ovp/frontend/ovp/plugins/vue3-tooltip.ts
- https://mobigen.atlassian.net/browse/FAB2023-1169
- https://mobigen.atlassian.net/browse/FAB2023-1155
- vue3-tooltip 세팅 및 예시 추가
=> [FAB2023-1155] Tooltip 패키지 세팅

project/ovp/server/src/main/java/com/mobigen/ovp/admin/service/ServiceController.java, project/ovp/server/src/main/java/com/mobigen/ovp/admin/service/ServiceService.java, project/ovp/server/src/main/java/com/mobigen/ovp/admin/service/client/ServiceClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/admin/service/client/response/ServiceBaseResponse.java, project/ovp/server/src/main/java/com/mobigen/ovp/admin/service/client/response/ServiceEntity.java, project/ovp/server/src/main/java/com/mobigen/ovp/admin/service/client/response/ServiceResponse.java, project/ovp/server/src/main/java/com/mobigen/ovp/glossary/client/response/Glossaries.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserController.java
- [FAB2023-1174](https://mobigen.atlassian.net/browse/FAB2023-1174)
[FAB2023-1174]: https://mobigen.atlassian.net/browse/FAB2023-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1174] feat: 서비스 관리 메인 페이지 API 개발

project/ovp/frontend/common/components/extends/modal/ModalComposition.ts, project/ovp/frontend/common/components/extends/tab/TabComposition.ts, project/ovp/frontend/ovp/components/datamodel-creation/datamodel-sample.json, project/ovp/frontend/ovp/components/datamodel-creation/item/data-model-list-item.vue, project/ovp/frontend/ovp/components/datamodel-creation/list/api/DataModelApiListComposition.ts, project/ovp/frontend/ovp/components/datamodel-creation/list/api/DataModelApiListProps.ts, project/ovp/frontend/ovp/components/datamodel-creation/list/api/accoridan/DataModelAccordianListComposition.ts, project/ovp/frontend/ovp/components/datamodel-creation/list/api/accoridan/data-model-accordian-list.vue, project/ovp/frontend/ovp/components/datamodel-creation/list/api/data-model-api-list.vue, project/ovp/frontend/ovp/components/datamodel-creation/list/base/DataModelListComposition.ts, project/ovp/frontend/ovp/components/datamodel-creation/list/base/data-model-list.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/add-detail-grid.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/add-kg.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/add-transfer.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/add.vue, project/ovp/frontend/ovp/components/search/detail-tab/profiling.vue, project/ovp/frontend/ovp/pages/portal/datamodel-creation/index.vue, project/ovp/frontend/ovp/store/datamodel-creation/index.ts, project/ovp/frontend/ovp/store/datamodel-creation/search.ts, project/ovp/frontend/ovp/utils/constant.ts, project/ovp/frontend/ovp/utils/intersection-observer.ts
- [FAB2023-926](https://mobigen.atlassian.net/browse/FAB2023-926)
- 데이터 생성 > 추가 모달 개발
- Tab 컴포넌트 수정
[FAB2023-926]: https://mobigen.atlassian.net/browse/FAB2023-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-926] 데이터 생성 > 추가 모달 개발

project/ovp/frontend/common/components/extends/grid/Grid.vue, project/ovp/frontend/common/components/extends/grid/GridComposition.ts, project/ovp/frontend/common/components/extends/grid/grid-units/ButtonRenderer.vue, project/ovp/frontend/common/pages/ag-grid/index.vue, project/ovp/frontend/ovp/components/admin/user/modal/add.vue, project/ovp/frontend/ovp/pages/portal/admin/user/index.vue, project/ovp/frontend/ovp/store/user/userStore.ts
- https://mobigen.atlassian.net/browse/FAB2023-1191
- https://mobigen.atlassian.net/browse/FAB2023-1193
- 사용자 관리 메인 페이지 화면 개발
- 사용자 관리 목록 구현
- 목록에 인피니티 스크롤 적용
- 사용자 추가 모달 컴포넌트 분리
- 마이페이지 개발구현 완료되면 사용자 관리 목록에서 마이페이지로 넘어가는 기능 확인
=> [FAB2023-1193] 사용자 관리 메인 페이지 화면 개발

project/ovp/frontend/ovp/store/manage/service/collection-log/index.ts
- log 모달 API 부분 수정( ui > API주소 변경)
=> fix : log 모달 API 부분 수정

project/ovp/frontend/ovp/components/admin/user/cell-renderer/delete-button.vue, project/ovp/frontend/ovp/pages/portal/admin/user/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-1192
- https://mobigen.atlassian.net/browse/FAB2023-1193
- admin 계정인 경우, 삭제버튼 비 노출 처리
=> [FAB2023-1192] feat: 사용자 관리 메인페이지 - admin 계정인 경우, 삭제버튼 비 노출 처리

project/ovp/frontend/ovp/components/admin/user/cell-renderer/delete-button.vue, project/ovp/frontend/ovp/pages/portal/admin/user/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-1192
- https://mobigen.atlassian.net/browse/FAB2023-1193
- SearchInput 컴포넌트 변경에 따른 코드 수정
- admin 계정인 경우, 삭제버튼 비 노출처리 누락코드 추가
=> [FAB2023-1192] feat: 사용자 관리 메인페이지 코드 수정

project/ovp/frontend/ovp/components/my-page/profile-box.vue, project/ovp/server/src/main/java/com/mobigen/ovp/mypage/MyPageService.java, project/ovp/server/src/main/java/com/mobigen/ovp/mypage/dto/response/UserInfoResponse.java
- [FAB2023-989](https://mobigen.atlassian.net/browse/FAB2023-989)
- [FAB2023-1037](https://mobigen.atlassian.net/browse/FAB2023-1037)
-  수정 대상 프로필 사진 아바타 처리
- 로그인 사용자, 수정대상 사용자에 따른 수정 버튼 활성화 처리
[FAB2023-989]: https://mobigen.atlassian.net/browse/FAB2023-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-1037]: https://mobigen.atlassian.net/browse/FAB2023-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-989] 마이페이지 메인페이지

project/ovp/frontend/common/components/extends/tab/TabComposition.ts, project/ovp/frontend/common/components/extends/tree/Tree.vue, project/ovp/frontend/common/components/extends/tree/tree.scss, project/ovp/frontend/ovp/components/govern/category/data-filter.vue, project/ovp/frontend/ovp/components/govern/category/data-model-add-modal.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/frontend/ovp/store/governance/Category/index.ts, project/ovp/frontend/ovp/utils/intersection-observer.ts
- https://mobigen.atlassian.net/browse/FAB2023-1168
- 인피니티 스크롤 동작 중 체크박스 전체 id 받도록 재갱신
=> [FAB2023-999] 데이터 추가 모달 - 인피니티 스크롤 동작 중 체크박스 전체 id 받도록 재갱신

project/ovp/frontend/ovp/components/admin/user/modal/add.vue, project/ovp/frontend/ovp/pages/portal/admin/user/index.vue, project/ovp/frontend/ovp/store/user/userStore.ts, project/ovp/frontend/ovp/type/user.ts, project/ovp/frontend/ovp/utils/constant.ts
- https://mobigen.atlassian.net/jira/software/c/projects/FAB2023/issues/FAB2023-1192
- https://mobigen.atlassian.net/jira/software/c/projects/FAB2023/issues/FAB2023-1193
- 사용자 추가 모달 구현
=> [FAB2023-1192] 사용자 추가 모달 화면 개발

project/ovp/frontend/common/assets/css/abstracts/_mixins-helper.scss, project/ovp/frontend/common/assets/css/components/_modal.scss, project/ovp/frontend/common/assets/css/components/common/_list.scss, project/ovp/frontend/common/components/extends/modal/Modal.vue, project/ovp/frontend/ovp/assets/css/pages/_creation.scss, project/ovp/frontend/ovp/assets/css/pages/_governance.scss, project/ovp/frontend/ovp/assets/css/pages/_search-detail.scss, project/ovp/frontend/ovp/assets/css/pages/_search.scss, project/ovp/frontend/ovp/components/datamodel-creation/modal/add.vue, project/ovp/frontend/ovp/components/govern/category/category-add-modal.vue, project/ovp/frontend/ovp/components/govern/category/category-change-modal.vue, project/ovp/frontend/ovp/components/govern/category/data-model-add-modal.vue, project/ovp/frontend/ovp/components/govern/glossary/modal/modal-glossary-dictionary.vue, project/ovp/frontend/ovp/components/govern/glossary/modal/modal-glossary.vue, project/ovp/frontend/ovp/components/manage/service/modal/modal-collection.vue, project/ovp/frontend/ovp/components/manage/service/modal/modal-log.vue, project/ovp/frontend/ovp/components/my-page/pw-reset-modal.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-984] 스타일 추가 이슈 퍼블리싱

project/ovp/frontend/ovp/store/user/userStore.ts, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserController.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserService.java
https://mobigen.atlassian.net/jira/software/c/projects/FAB2023/issues/FAB2023-1192
https://mobigen.atlassian.net/jira/software/c/projects/FAB2023/issues/FAB2023-1194
- 랜덤 비밀번호 발급 API 구현
- 사용자 이름 중복 체크 API 구현
- 사용자 정보 추가 API 구현
- 사용자 추가 모달에 구현된 API 연결
=> [FAB2023-1192] 사용자 추가 모달 API 개발

project/ovp/docker/Dockerfile, project/ovp/docker/template/service/docker-conf/application-all.yml, project/ovp/docker/template/service/docker-conf/application.yml, project/ovp/docker/template/service/docker-conf/docker.conf, project/ovp/frontend/ovp/components/datamodel-creation/modal/add.vue, project/ovp/frontend/ovp/components/my-page/pw-reset-modal.vue, project/ovp/frontend/ovp/layouts/default.vue, project/ovp/frontend/ovp/pages/portal/datamodel-creation/index.vue, project/ovp/frontend/ovp/pages/portal/my-page/index.vue, project/ovp/frontend/ovp/plugins/vue-final-modal.ts, project/ovp/scripts/build-docker.sh, project/ovp/server/pom.xml, project/ovp/server/src/main/java/com/mobigen/framework/configuration/WebSecurityConfiguration.java, project/ovp/server/src/main/java/com/mobigen/framework/filter/NuxtSSRStaticUrlFilter.java, project/ovp/server/src/main/java/com/mobigen/framework/security/JwtFilter.java, project/ovp/server/src/main/java/com/mobigen/framework/security/LocalLoginFilter.java, project/ovp/server/src/main/java/com/mobigen/framework/utility/restful/OpenFeignConfig.java, project/ovp/server/src/main/java/com/mobigen/ovp/ViewController.java, project/ovp/server/src/main/java/com/mobigen/ovp/ViewErrorController.java, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthService.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/OvpProperties.java, project/ovp/server/src/main/java/com/mobigen/ovp/email/EmailUtil.java, project/ovp/server/src/main/resources/application.yml, project/ovp/server/src/main/resources/templates/ovp_pwReset.html, project/ovp/start.sh
- [FAB2023-1155](https://mobigen.atlassian.net/browse/FAB2023-1155)
- docker config 수정
- 사용자 인증에 따른 리다이랙트 처리
- 배포 시 template 엔진 이슈로 인한 비밀번호 재발급 메일 처리 변경
- JDK 버전 변경
[FAB2023-1155]: https://mobigen.atlassian.net/browse/FAB2023-1155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1155] 배포 준비

project/ovp/frontend/ovp/components/search/detail-tab/default-info.vue, project/ovp/frontend/ovp/components/search/detail-tab/lineage.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue, project/ovp/frontend/ovp/store/search/detail/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/TablesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/response/DataModelDetailResponse.java
=> [FAB2023-898] 데이터 모델 상세 / 태그, 용어 목록 연결

project/ovp/frontend/common/components/extends/step/StepComposition.ts, project/ovp/frontend/ovp/pages/portal/manage/service/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-1041
- watch 코드 computed로 수정
- modal open 방식 변경
=> [FAB2023-1003] 서비스 추가 모달 동작 방식 변경

project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java
=> [FAB2023-898] 북마크한 데이터 안나오는 문제 수정

project/ovp/frontend/ovp/components/manage/service/modal/modal-service/modal-service.vue, project/ovp/frontend/ovp/pages/portal/manage/service/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-1041
- modal close 동작 안함 수정
=> [FAB2023-1033] fix : 서비스 추가 model open 방식 수정

project/ovp/frontend/common/components/extends/modal/Modal.vue, project/ovp/frontend/common/components/extends/modal/ModalProps.ts, project/ovp/frontend/ovp/components/govern/category/category-add-modal.vue, project/ovp/frontend/ovp/components/govern/category/category-change-modal.vue, project/ovp/frontend/ovp/components/govern/category/data-model-add-modal.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-1189
- 모달 열고 닫기 코드 수정, modal props 옵셔널 변경
=> [FAB2023-999] 모달 열고 닫기 코드 수정, modal props 옵셔널 변경

project/ovp/frontend/common/components/extends/menu-seach/tree/MenuSearchTreeProps.ts, project/ovp/frontend/common/components/extends/menu-seach/tree/menu-search-tree.vue, project/ovp/frontend/ovp/components/common/resource-box/resource-box-props.ts, project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/components/search/detail-tab/lineage.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue, project/ovp/frontend/ovp/store/search/detail/index.ts, project/ovp/frontend/ovp/store/search/detail/lineage/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/constants/ModelType.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ContainersClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/StorageColumn.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/Tables.java, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/response/DataModelDetailCategory.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/response/DataModelDetailResponse.java
=> [FAB2023-898] fix: 카테고리 수정 리스트 데이터 면결 및 스토리지 상세, 변경 API 추가

project/ovp/frontend/common/assets/css/components/_modal.scss, project/ovp/frontend/common/pages/design-guide/pages/guide-progressbar.vue, project/ovp/frontend/ovp/assets/css/layouts/_header.scss, project/ovp/frontend/ovp/components/datamodel-creation/modal/add.vue, project/ovp/frontend/ovp/components/govern/category/category-add-modal.vue, project/ovp/frontend/ovp/components/govern/category/category-change-modal.vue, project/ovp/frontend/ovp/components/govern/category/data-model-add-modal.vue, project/ovp/frontend/ovp/components/govern/glossary/modal/modal-glossary-dictionary.vue, project/ovp/frontend/ovp/components/govern/glossary/modal/modal-glossary.vue, project/ovp/frontend/ovp/components/manage/service/modal/modal-collection.vue, project/ovp/frontend/ovp/components/manage/service/modal/modal-log.vue, project/ovp/frontend/ovp/components/my-page/pw-reset-modal.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-692] 스타일 추가 이슈 퍼블리싱 2차

project/ovp/frontend/ovp/assets/css/pages/_main.scss, project/ovp/frontend/ovp/pages/index.vue, project/ovp/frontend/ovp/store/main/mainStore.ts
- https://mobigen.atlassian.net/browse/FAB2023-1016
- https://mobigen.atlassian.net/browse/FAB2023-998
- 최근 탐색 데이터 정보 삭제
- 추천 많은 데이터 위치, 개수 수정
=> [FAB2023-998] 최근 탐색 데이터 삭제, 추천 많은 데이터 위치, 개수 수정 

project/ovp/frontend/ovp/components/search/detail-tab/default-info.vue, project/ovp/frontend/ovp/components/search/detail-tab/lineage.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue, project/ovp/frontend/ovp/store/search/detail/index.ts, project/ovp/frontend/ovp/store/search/detail/lineage/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/Lineage.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/Node.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/response/DataModelDetailLineageTableResponse.java
=> [FAB2023-898] fix: 데이터모델, 융합모델, 스토리지 리니지 그래프 제대라 안나오는 문제 수정

project/ovp/frontend/ovp/components/search/data-filter.vue
- 스토리지 일때 표시되는 필터 숨김 처리 (데이터베이스, 스키마 숨김)
=> [FAB2023-898] fix : 탐색 - 스토리지 일때 필터 표시 수정

project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ServicesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageController.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- https://mobigen.atlassian.net/browse/FAB2023-1185
- 메타데이터, 프로파일러 api 1차 구현
=> [FAB2023-1003] 메타데이터,프로파일러 등록/수정 backend 구현

project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ServicesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageController.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- Issue (버그 수정 등) (코드원복)
- https://mobigen.atlassian.net/browse/FAB2023-1185
=> [FAB2023-1003] fix : 코드 오류 임시 수정 (주석처리)

project/ovp/frontend/ovp/utils/intersection-observer.ts
- https://mobigen.atlassian.net/browse/FAB2023-1168
- modal 사용방법 변경에 따른 infinite scroll scrollTop 기능 수정
=> [FAB2023-999] fix : modal 에 infinite scroll 오작동 수정

project/ovp/frontend/ovp/components/govern/category/data-model-add-modal.vue, project/ovp/frontend/ovp/composables/intersectionObserverHelper.ts, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/frontend/ovp/pages/portal/manage/service/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-1168
- modal 사용방법 변경에 따른 infinite scroll 처리 기능 수정
=> [FAB2023-999] fix : modal 에 infinite scroll 오작동 2차 수정

project/ovp/frontend/ovp/layouts/sidebar.vue
- https://mobigen.atlassian.net/browse/FAB2023-998
- https://mobigen.atlassian.net/browse/FAB2023-1162
- 관리메인/서비스관리/사용자관리 페이지 진입시 좌측 sidebar 메뉴에 '관리' 부분에 선택 효과 없는 오류 수정
=> [FAB2023-998] fix : 메뉴 - '관리' 선택 효과 추가

project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ServicesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageController.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- https://mobigen.atlassian.net/browse/FAB2023-1185
- 오류 수정
- startDate, name backend 처리 추가
=> [FAB2023-1003] 메타데이터,프로파일러 등록/수정 backend 오류 수정 외 1건

project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ContainersClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/DatabaseClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/DatabaseSchemasClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageController.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- https://mobigen.atlassian.net/browse/FAB2023-1177
- 서비스 저장소 탭 내의 '서비스 리스트' 목록 조회 API 구현
=> [FAB2023-1177] feat : 서비스 관리 저장소 탭 하위 서비스 목록 API 구현

project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ServicesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageController.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- https://mobigen.atlassian.net/browse/FAB2023-1180
- databaseService name 으로 조회
- storageService name 으로 조회
- databaseService 데이터 수정
- storageService 데이터 수정
=> [FAB2023-1003] feat: 서비스 관리 연결정보 탭 API 개발

project/ovp/frontend/common/assets/css/components/_table.scss, project/ovp/frontend/ovp/assets/css/layouts/_header.scss, project/ovp/frontend/ovp/assets/css/layouts/_sidebar.scss, project/ovp/frontend/ovp/components/govern/category/data-model-add-modal.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1213] 테스트 버그 수정 - 퍼블리싱

project/ovp/frontend/ovp/components/manage/service/modal/modal-service/ModalServiceProps.ts, project/ovp/frontend/ovp/components/manage/service/modal/modal-service/modal-service.vue, project/ovp/frontend/ovp/components/manage/service/modal/modal-service/step/step1.vue, project/ovp/frontend/ovp/components/manage/service/modal/modal-service/step/step2.vue, project/ovp/frontend/ovp/components/manage/service/modal/modal-service/step/step3.vue
- https://mobigen.atlassian.net/browse/FAB2023-1041
=> [FAB2023-1033] 연결테스트 화면 표시 오류 수정

project/ovp/server/src/main/java/com/mobigen/ovp/common/ModelConvertUtil.java
- resource-box 에 owner 제대로 표시 안됨 수정
=> [FAB2023-898] fix : search-list owner 표시 부분 수정

project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ServicesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageController.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- https://mobigen.atlassian.net/browse/FAB2023-1185
- 메타데이터, 프로파일러 수정시 사용할 데이터 조회 API 구현
=> [FAB2023-1003] feat : 메타데이터/프로파일러 조회 api 구현

project/ovp/frontend/ovp/components/common/resource-box/resource-box-props.ts, project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/components/search/detail-default.vue, project/ovp/frontend/ovp/components/search/detail-tab/default-info.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue, project/ovp/frontend/ovp/store/search/detail/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/category/CategoryController.java, project/ovp/server/src/main/java/com/mobigen/ovp/category/CategoryService.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/TablesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/Tag.java, project/ovp/server/src/main/java/com/mobigen/ovp/glossary/client/GlossaryClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/glossary/client/dto/TermDto.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/request/DataModelDetailTagDto.java
=> [FAB2023-898] 데이터모델 태그 추가 API 추가

project/ovp/frontend/common/assets/css/components/_modal.scss, project/ovp/frontend/common/components/extends/tab/tab.scss, project/ovp/frontend/ovp/assets/css/pages/_admin.scss, project/ovp/frontend/ovp/assets/css/pages/_submit-form.scss
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1215] fix: 버그 이슈처리 - 퍼블리싱

project/ovp/frontend/ovp/components/manage/service/modal/modal-service/ModalServiceComposition.ts, project/ovp/frontend/ovp/store/manage/service/modal/index.ts
- https://mobigen.atlassian.net/browse/FAB2023-1041
- 기획 변경사항 반영
=> [FAB2023-1033] feat : 서비스 추가 모달 기획 변경사항 반영

project/ovp/frontend/ovp/components/manage/service/connection-info.vue, project/ovp/frontend/ovp/components/manage/service/modal/modal-service/ModalServiceComposition.ts, project/ovp/frontend/ovp/components/manage/service/modal/modal-service/ModalServiceProps.ts, project/ovp/frontend/ovp/components/manage/service/modal/modal-service/modal-service.vue, project/ovp/frontend/ovp/package-lock.json, project/ovp/frontend/ovp/package.json, project/ovp/frontend/ovp/store/manage/service/index.ts, project/ovp/frontend/ovp/store/manage/service/modal/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ServicesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageController.java
- https://mobigen.atlassian.net/browse/FAB2023-1179
- 서비스 관리 연결정보 탭 화면개발
=> [FAB2023-1003] feat: 서비스 관리 연결정보 탭 화면개발

project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/components/search/detail-default.vue, project/ovp/frontend/ovp/components/search/detail-tab/default-info.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue, project/ovp/frontend/ovp/store/search/detail/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ContainersClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/TablesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java
- 데이터모델상세/ 추천, 비추천, 북마크 기능 추가
- 데이터모델상세/ 용어 수정이 안되는 문제 수정
-  데이터모델상세/ 개발중인 탭에 alert 추가
- 데이터 모델 상세 권한에 따른 기능 활성/비활성 처리
=> [FAB2023-898] 데이터모델상세/ 추천, 비추천, 북마크 기능 추가

project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/TablesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- https://mobigen.atlassian.net/browse/FAB2023-1177
- metadata 일때 표시되는 목록 항목 수정
=> [FAB2023-1177] fix : 서비스 관리 저장소 탭 하위 서비스 목록 API 수정

project/ovp/frontend/ovp/components/search/data-filter.vue, project/ovp/frontend/ovp/layouts/header.vue, project/ovp/frontend/ovp/pages/index.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/frontend/ovp/pages/portal/manage/index.vue, project/ovp/frontend/ovp/pages/portal/search/index.vue
=> refactor: 버그리스트 이슈처리 

project/ovp/frontend/common/components/extends/search-input/SearchInput.vue, project/ovp/frontend/common/pages/index.vue, project/ovp/frontend/common/pages/search-input/index.vue, project/ovp/frontend/ovp/components/govern/category/data-model-add-modal.vue, project/ovp/frontend/ovp/layouts/header.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-1217
=> [FAB2023-999] search-input 컴포넌트 버그 이슈처리 

project/ovp/frontend/ovp/components/login/login.vue, project/ovp/frontend/ovp/layouts/sidebar.vue, project/ovp/frontend/ovp/store/common/menu.ts, project/ovp/server/src/main/java/com/mobigen/ovp/menu/MenuController.java, project/ovp/server/src/main/java/com/mobigen/ovp/menu/MenuService.java, project/ovp/server/src/main/java/com/mobigen/ovp/menu/entity/MenuEntity.java, project/ovp/server/src/main/java/com/mobigen/ovp/menu/repository/MenuRepository.java
- 로그인페이지에서 비밀번호 인풋 눈모양 토글 버튼클릭시 아이콘 전환 안되는 이슈 처리
=> fix: 로그인페이지 - 비밀번호 인풋 눈모양 토글 버튼 아이콘 전환 이슈 처리

project/ovp/frontend/ovp/assets/css/layouts/_common.scss, project/ovp/frontend/ovp/assets/css/layouts/_section.scss, project/ovp/frontend/ovp/assets/css/pages/_governance.scss, project/ovp/frontend/ovp/pages/portal/govern/index.vue, project/ovp/frontend/ovp/pages/portal/manage/index.vue, project/ovp/frontend/ovp/pages/portal/search/top-bar.vue
=> [FAB2023-1215] 버그 수정 - 퍼블리싱

project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/components/search/detail-tab/default-info.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue, project/ovp/frontend/ovp/store/search/detail/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/ModelConvertUtil.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/Tables.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/response/DataModelDetailResponse.java
=> [FAB2023-898] 데이터모델상세/ 소유자, 카테고리 위치 틀어지는 문제 수정 및 서비스 아이콘 추가

project/ovp/frontend/ovp/components/manage/service/ingestions.vue, project/ovp/frontend/ovp/components/manage/service/service-info.vue, project/ovp/frontend/ovp/store/manage/service/index.ts, project/ovp/frontend/ovp/type/service.ts, project/ovp/frontend/ovp/utils/constant.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ServicesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/Ingestion.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageController.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/client/response/IngestionResponse.java
- [FAB2023-1212](https://mobigen.atlassian.net/browse/FAB2023-1212)
[FAB2023-1212]: https://mobigen.atlassian.net/browse/FAB2023-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1212] feat: 서비스 관리 수집 탭 API 개발

project/ovp/frontend/ovp/store/datamodel-creation/search.ts, project/ovp/server/src/main/java/com/mobigen/ovp/main/MainService.java, project/ovp/server/src/main/java/com/mobigen/ovp/model_creation/ModelCreationController.java, project/ovp/server/src/main/java/com/mobigen/ovp/model_creation/ModelCreationService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserClient.java
- [FAB2023-926](https://mobigen.atlassian.net/browse/FAB2023-926)
- Main > 북마크 API 수정
- 데이터 모델 생성 > 목록 리스트 API
- 데이터 모델 생성 > My 리스트 API
[FAB2023-926]: https://mobigen.atlassian.net/browse/FAB2023-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-926] 데이터 모델 생성 API 개발

project/ovp/frontend/ovp/store/search/common.ts
- https://mobigen.atlassian.net/browse/FAB2023-1217 
- https://mobigen.atlassian.net/browse/FAB2023-1216
- https://docs.google.com/spreadsheets/d/1FmZbQE3bYGsgK-g5WaIyP_Ck-jNq57OwBFxSW_c4kbQ/edit?gid=550650835#gid=550650835&range=2:2
=> [FAB2023-1216] 메인 - 탭 개수 초기화 적용

project/ovp/frontend/common/components/extends/tree/Tree.vue, project/ovp/frontend/common/components/extends/tree/TreeComposition.ts, project/ovp/frontend/common/components/extends/tree/TreeProps.ts, project/ovp/frontend/ovp/components/govern/category/category-change-modal.vue, project/ovp/frontend/ovp/components/govern/category/data-model-add-modal.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/frontend/ovp/store/governance/Category/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/category/CategoryController.java, project/ovp/server/src/main/java/com/mobigen/ovp/category/CategoryService.java
- https://mobigen.atlassian.net/browse/FAB2023-1168
- API 개발
- 버튼 비활성화 체크, 모델 목록 미체크 했을 때 alert 알림 등
=> [FAB2023-999] 카테고리 데이터 모델 추가/변경 API 개발

project/ovp/frontend/common/components/extends/tree/tree.scss, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1213] tree, 페이지 틀어짐 수정 퍼블리싱

project/ovp/frontend/ovp/components/manage/service/ingestions.vue, project/ovp/frontend/ovp/components/manage/service/modal/collection/modal-collection.vue, project/ovp/frontend/ovp/components/manage/service/modal/collection/step/config-step.vue, project/ovp/frontend/ovp/components/manage/service/modal/collection/step/config/database-profiler.vue, project/ovp/frontend/ovp/components/manage/service/modal/collection/step/schedule-step.vue, project/ovp/frontend/ovp/store/manage/service/collection-add/index.ts
- [FAB2023-995](https://mobigen.atlassian.net/browse/FAB2023-995)
- [FAB2023-1184](https://mobigen.atlassian.net/browse/FAB2023-1184)
- 수집 모달 수정
[FAB2023-995]: https://mobigen.atlassian.net/browse/FAB2023-995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-1184]: https://mobigen.atlassian.net/browse/FAB2023-1184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-995] 서비스 관리 프로파일러 수집 수정 모달 화면 개발 

project/ovp/frontend/ovp/store/manage/service/modal/index.ts
=> fix: 서비스 추가 모달 - 서비스명 중복체크 이슈 처리

project/ovp/frontend/ovp/components/manage/service/ingestions.vue, project/ovp/frontend/ovp/components/manage/service/service-info.vue, project/ovp/frontend/ovp/components/manage/service/service-list.vue, project/ovp/frontend/ovp/store/manage/service/index.ts, project/ovp/frontend/ovp/type/service.ts, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/client/response/ServiceResponse.java
- [FAB2023-1212](https://mobigen.atlassian.net/browse/FAB2023-1212)
[FAB2023-1212]: https://mobigen.atlassian.net/browse/FAB2023-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1212] fix: 서비스 API & 화면 버그 수정

project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/components/manage/service/modal/log.vue, project/ovp/frontend/ovp/store/main/mainStore.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/ModelConvertUtil.java, project/ovp/server/src/main/java/com/mobigen/ovp/main/MainService.java
- 서비스관리/ 로그 모달 사이즈 변경 및 로그 readonly 추가
- 메인/ 북마크한 데이터 3개만 안나오는 문제 수정
=> [FAB2023-1218] OVP 2차 버그 수정

project/ovp/frontend/ovp/store/main/mainStore.ts, project/ovp/frontend/ovp/store/search/common.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/ModelConvertUtil.java, project/ovp/server/src/main/java/com/mobigen/ovp/main/MainController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchService.java
- 메인 index:'all' 로 처리 관련 화면 오류 수정
- 메인 index all 처리 수정
- 메인 depth 처리 테스트 코드 삭제 외
=> [FAB2023-1218] OVP 3차 버그 수정

project/ovp/frontend/ovp/components/manage/service/modal/modal-service/ModalServiceComposition.ts
=> [FAB2023-1157] feat : 서비스추가(postgreSql) 필수 옵션 추가

project/ovp/frontend/ovp/store/glossary/index.ts, project/ovp/frontend/ovp/store/my-page/myPageStore.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/ModelConvertUtil.java, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchController.java
- admin 계정인 경우 나의 데이터 index:'all'로 조회하기 때문에 modelConvertUtil 에서 에러남. 예외처리 함.
=> [FAB2023-1157] fix : 마이페이지 -> 나의 데이터 index:'all' 예외 처리 추가

project/ovp/frontend/ovp/components/common/preview/preview.vue, project/ovp/server/src/main/java/com/mobigen/ovp/common/ModelConvertUtil.java
- 탐색/ 목록에서 displayName이 나오게 처리
- 탐색/ 프리뷰에서 카테고리 태그 나오는 문제 수정
=> [FAB2023-1218] OVP 4차 버그 수정

project/ovp/docker/template/service/docker-conf/application-all.yml, project/ovp/frontend/ovp/layouts/login.vue, project/ovp/frontend/ovp/package-lock.json, project/ovp/frontend/ovp/package.json, project/ovp/frontend/ovp/pages/portal/login/error/index.vue, project/ovp/frontend/ovp/pages/portal/login/pw-reset/index.vue, project/ovp/server/src/main/java/com/mobigen/ovp/email/EmailController.java, project/ovp/server/src/main/java/com/mobigen/ovp/email/EmailService.java, project/ovp/server/src/main/resources/application.yml
- Issue
- npm generate 오류 수정
- 비밀번호 재설정 메일전송 버그 수정
=> 비밀번호 재설정 메일 전송 관련 버그 수정

project/ovp/frontend/common/components/extends/tree/Tree.vue, project/ovp/frontend/common/components/extends/tree/TreeComposition.ts, project/ovp/frontend/common/components/extends/tree/TreeProps.ts, project/ovp/frontend/ovp/components/govern/category/category-change-modal.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/frontend/ovp/store/governance/Category/index.ts, project/ovp/frontend/ovp/utils/constant.ts, project/ovp/server/src/main/java/com/mobigen/ovp/category/CategoryService.java, project/ovp/server/src/main/java/com/mobigen/ovp/category/repository/CategoryRepository.java, project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchService.java
- filter 조회 all -> table, container 조회로 변경
- 카테고리 변경/데이터 모델 추가 버튼 제어 수정
- 미분류 카테고리 기능 추가
- 최하위 depth 카테고리 일때만 우측 데이터 모델 영역 표시되도록 수정.
=> [FAB2023-1157] 버그리스트 이슈 처리

project/ovp/frontend/ovp/components/login/sign-up.vue, project/ovp/frontend/ovp/utils/constant.ts, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthService.java
- 20240827_08
- 20240902_14
- 이메일 아이디 중복시 안내문구 표시
- 이름에 들어가는 값을 name 이 아닌 displayName 으로 변경
=> fix: 회원가입 이슈 처리

project/ovp/frontend/ovp/components/manage/service/connection-info.vue, project/ovp/frontend/ovp/components/manage/service/modal/modal-service/ModalServiceComposition.ts, project/ovp/frontend/ovp/components/manage/service/service-info.vue, project/ovp/frontend/ovp/components/manage/service/service-list.vue, project/ovp/frontend/ovp/store/manage/service/index.ts, project/ovp/frontend/ovp/store/manage/service/modal/index.ts
- 서비스 목록 및 서비스 정보 헤더에 서비스 유형 아이콘 출력
=> fix: 서비스 목록 및 서비스 정보 헤더 - 서비스 유형 아이콘 출력

project/ovp/frontend/ovp/components/search/detail-default.vue, project/ovp/frontend/ovp/pages/portal/search/top-bar.vue, project/ovp/frontend/ovp/store/manage/service/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ServicesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/mypage/MyPageService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageController.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- 데이터모델상세/ 태그목록에서openmetadata 기본 classification  PII 안나오게 처리
- 마이페이지/ email 수정
- 탐색/ 그래프 선택시 개발중입니다 alert 추가
- 데이터모델상세/ 링크 복사 안되는 문제 수정
- 서비스 관리/ 스토리지서비스가 삭제 안되는 문제 수정
=> [FAB2023-1218] OVP 5차 버그 수정

project/ovp/frontend/ovp/layouts/header.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/server/src/main/java/com/mobigen/ovp/mypage/MyPageService.java, project/ovp/server/src/main/resources/application.yml
- 회원가입/ 배포환경에서 회원 가입시 이름 채크 하는 부분에서 401에러 발생하는 문제 수정
- 마이페이지/ 사용자일 경우 eamil이 마스킹 처리되어서 우리 DB에서 조회 후 데이터 추가
- 카테고리/ 카테고리 수정 placeholder 문구 수정
- 헤더/ 마이페이지 접근시 개발중입니다. alert 추가
=> [FAB2023-1218] OVP 6차 버그 수정 

project/ovp/server/src/main/java/com/mobigen/ovp/user/UserService.java
=> fix: 사용자 관리에서 사용자 삭제시 영구삭제

project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- 서비스 - 목록 - storage 데이터 '저장소' 목록 기준 변경 ( 2 depth -> 3 depth )
=> [FAB-2023-1157] feat : storage 데이터 저장소 목록 3depth 데이터 표시되도록 수정

project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- database : 2depth name
- storage : 1depth name
=> [FAB2023-1157] fix : 서비스 저장소 리스트 구분 값 수정

project/ovp/server/src/main/java/com/mobigen/ovp/category/repository/CategoryRepository.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/ModelConvertUtil.java
=> [FAB2023-1157] fix : 데이터 상세 카테고리 미분류 데이터 외에 제대로 표시 안됨 수정

project/ovp/frontend/ovp/components/manage/service/modal/log.vue, project/ovp/frontend/ovp/components/search/detail-default.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue, project/ovp/frontend/ovp/store/search/detail/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ContainersClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/glossary/client/GlossaryClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/response/DataModelDetailSampleDataResponse.java
- 데이터 모델 삭제 기능 추가
- 클립보드 모듈 교체
- 샘플데이터가 없을 때 데이터 안나오는 문제 수정
- 비정형 데이터 모델일때 누락된 탭 보이게 처리
- 용어 URL 변경
=> [FAB2023-1218] OVP 7차 버그 수정 

project/ovp/frontend/ovp/components/manage/service/connection-info.vue, project/ovp/frontend/ovp/components/manage/service/modal/log.vue, project/ovp/frontend/ovp/components/search/detail-default.vue, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/client/response/ServiceResponse.java
- 클립보드 복사 안되는 문제 2차 수정
- 서비스관리/ 연결정보 탭에서 연결정보 수정 버튼이 스타일이 다른 문제 수정
- 서비스관리/ 태그의 displayName이 안나오는 문제 수정
=> [FAB2023-1218] OVP 8차 버그 수정 

project/ovp/frontend/ovp/components/manage/service/linkDetailComponent.vue, project/ovp/frontend/ovp/components/manage/service/repository.vue, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
=> [FAB2023-1157] 이슈리스트 처리

project/ovp/frontend/common/components/extends/menu-seach/tree/contents/menu-search-tree-contents.vue, project/ovp/frontend/common/components/extends/tree/TreeComposition.ts, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/frontend/ovp/store/search/common.ts
=> Isu fix skysora

project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- index 제대로 표시 안됨 수정
- database 일부 항목만 표시됨 수정
=> [FAB2023-1157] fix : 서비스 - 저장소 탭 index 제대로 표시 안됨 외

project/ovp/frontend/ovp/components/manage/service/modal/log.vue, project/ovp/frontend/ovp/pages/portal/datamodel-creation/index.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue, project/ovp/frontend/ovp/store/search/detail/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ContainersClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/DataModel.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/response/DataModelDetailSampleDataResponse.java
- 데이터모델상세/ 스토리지 샘플데이터 API 추가
- 데이터모델상세/ 스토리지일때 샘플탭 나오게 처리
- 데이터모델생성/ 메뉴 진입시 개발중입니다. alert 추가
- 서비스관리/ 수집 로그 모달에서 로그 복사 버튼 임시 숨김
=> [FAB2023-1218] OVP 9차 버그 수정 

project/ovp/frontend/ovp/assets/css/layouts/_sidebar.scss
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1214] side-bar 애니메이션 수정

project/ovp/frontend/common/assets/css/abstracts/_fonts.scss, project/ovp/frontend/common/assets/css/abstracts/_z-index.scss, project/ovp/frontend/ovp/assets/css/layouts/_sidebar.scss, project/ovp/frontend/ovp/components/manage/service/repository.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1213] 버그수정 side-bar 이슈 개선 등 

project/ovp/frontend/ovp/layouts/sidebar.vue
- ex) 탐색 화면에서 메뉴의 '탐색' 을 눌렀을때 새로고침 처리
=> [FAB2023-1157] feat : 현재 페이지의 메뉴를 눌렀을때 화면 새로고침 되도록 처리

project/ovp/frontend/common/assets/css/components/_button.scss, project/ovp/frontend/common/assets/css/components/_dropdown.scss, project/ovp/frontend/common/assets/css/components/_editable-group.scss, project/ovp/frontend/common/assets/css/components/_menu.scss, project/ovp/frontend/common/components/extends/notification/Notification.scss, project/ovp/frontend/common/components/extends/pagination/Pagination.scss, project/ovp/frontend/common/components/extends/select-box/select.scss, project/ovp/frontend/ovp/assets/css/layouts/_common.scss, project/ovp/frontend/ovp/assets/css/layouts/_section.scss, project/ovp/frontend/ovp/components/manage/user/cell-renderer/delete-button.vue, project/ovp/frontend/ovp/pages/portal/manage/user/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1214] 추가 이슈 해결 - 퍼블리싱

project/ovp/server/src/main/java/com/mobigen/ovp/category/CategoryService.java
- 미분류 등록시, name값과 displayName 값을 "미분류"로 저장
=> fix: 거버넌스>카테고리 - 미분류 등록시, name 값과 displayName 값을 "미분류" 로 저장

project/ovp/frontend/common/components/extends/tree/tree.scss, project/ovp/frontend/ovp/assets/css/component/_resource-box.scss, project/ovp/frontend/ovp/assets/css/main.scss, project/ovp/frontend/ovp/assets/css/pages/_governance.scss, project/ovp/frontend/ovp/assets/css/pages/_manage.scss, project/ovp/frontend/ovp/assets/css/pages/_my-page.scss, project/ovp/frontend/ovp/pages/_pub/govern/category/index.vue, project/ovp/frontend/ovp/pages/_pub/govern/glossary/index.vue, project/ovp/frontend/ovp/pages/_pub/govern/tags/index.vue, project/ovp/frontend/ovp/pages/_pub/manage/overview/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1214] 버그리스트 및 추가 이슈 해결 - 퍼블리싱

project/ovp/frontend/common/components/extends/tree/Tree.vue, project/ovp/frontend/common/components/extends/tree/TreeComposition.ts, project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/components/datamodel-creation/list/api/data-model-api-list.vue, project/ovp/frontend/ovp/components/govern/category/category-change-modal.vue, project/ovp/frontend/ovp/components/govern/category/data-model-add-modal.vue, project/ovp/frontend/ovp/components/login/PasswordComposition.ts, project/ovp/frontend/ovp/components/login/sign-up.vue, project/ovp/frontend/ovp/components/my-page/pw-reset-modal.vue, project/ovp/frontend/ovp/composables/intersectionObserverHelper.ts, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/frontend/ovp/pages/portal/manage/user/index.vue, project/ovp/frontend/ovp/pages/portal/my-page/index.vue, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/frontend/ovp/store/common/paging.ts, project/ovp/frontend/ovp/store/datamodel-creation/search.ts, project/ovp/frontend/ovp/store/governance/Category/index.ts, project/ovp/frontend/ovp/utils/intersection-observer.ts, project/ovp/server/src/main/java/com/mobigen/ovp/category/CategoryService.java
- infinite scroll 수정
- 카테고리 query 수정
- 카테고리 검색어 처리 수정
- 회원가입 validation 처리 수정
- 카테고리 모델 추가 후 목록에 검색어 남아있음 수정
=> [FAB2023-1157] 버그리스트 이슈처리

project/ovp/frontend/common/components/extends/menu-seach/tree/contents/MenuSearchTreeContentsComposition.ts, project/ovp/frontend/common/components/extends/tree/Tree.vue, project/ovp/frontend/common/components/extends/tree/TreeComposition.ts, project/ovp/frontend/ovp/components/govern/category/data-model-add-modal.vue, project/ovp/frontend/ovp/components/login/login.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue, project/ovp/frontend/ovp/pages/portal/login/pw-reset/index.vue, project/ovp/frontend/ovp/store/governance/Category/index.ts
- https://mobigen.atlassian.net/browse/FAB2023-1220
- 20240910_01 (상세 내용 설명 타이틀 추가, 설명없는 경우 '-' 처리 )
=> [FAB2023-1220] 사용성 테스트 버전 버그 수정

project/ovp/frontend/ovp/components/datamodel-creation/modal/save.vue, project/ovp/frontend/ovp/pages/portal/datamodel-creation/index.vue, project/ovp/frontend/ovp/store/datamodel-creation/save.ts, project/ovp/server/src/main/java/com/mobigen/ovp/model_creation/ModelCreationService.java
- [FAB2023-925](https://mobigen.atlassian.net/browse/FAB2023-925)
- [FAB2023-1012](https://mobigen.atlassian.net/browse/FAB2023-1012)
- 돌핀 api 테스트
- 카테고리 항목 default 미분류 처리
[FAB2023-925]: https://mobigen.atlassian.net/browse/FAB2023-925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-1012]: https://mobigen.atlassian.net/browse/FAB2023-1012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-925] 데이터 모델 저장

project/ovp/frontend/ovp/components/my-page/profile-box.vue, project/ovp/frontend/ovp/pages/portal/my-page/index.vue, project/ovp/server/src/main/java/com/mobigen/ovp/auth/AuthService.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserController.java, project/ovp/server/src/main/java/com/mobigen/ovp/user/UserService.java
- 20240906_44
- 20240906_45
- 20240911_15
- 20240913_03
- 나의북마크 실시간 검색되도록 처리
- 표시이름, 설명 값 없을경우 텍스트 처리
- 사용자 관리페이지에서 사용자추가 후 상세페이지 들어가면 정보 가져오지 못하는 이슈 처리
=> feat: 마이페이지 관련 버그리스트 이슈 처리

project/ovp/frontend/ovp/components/classification/classification-list/tagList.vue, project/ovp/frontend/ovp/components/classification/modal/classification-create.vue, project/ovp/frontend/ovp/components/classification/modal/tag-create.vue, project/ovp/frontend/ovp/store/classification/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/classification/ClassificationService.java, project/ovp/server/src/main/java/com/mobigen/ovp/classification/ClassificationTagService.java, project/ovp/server/src/main/java/com/mobigen/ovp/classification/client/dto/classification/tag/ClassificationTagAddResponse.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ClassificationClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ClassificationTagsClient.java
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 태그 추가에 필요한 중복 제거과정 API추가
- 태그list name값 안보이는 문제 해결
- 태그 추가 모달 에러메시지 화면 개발 추가
- 태그 수정 
- 인피니트 스크롤[분류list / 태그list]
=> refactor: 태그 추가 API 중복처리 & 화면 개발 추가 및 태그목록 화면내 문 수정

project/ovp/frontend/ovp/components/login/login.vue
=> fix: 로그인 화면 버그 수정

project/ovp/frontend/ovp/components/my-page/profile-box.vue, project/ovp/frontend/ovp/pages/portal/my-page/index.vue, project/ovp/frontend/ovp/store/my-page/myPageStore.ts
- 스토리지 타입의 모델 클릭할때 미리보기 나타나도록 처리
=> fix: 마이페이지 버그 수정

project/ovp/frontend/ovp/components/manage/service/ingestions.vue, project/ovp/frontend/ovp/components/manage/service/service-info.vue, project/ovp/frontend/ovp/components/manage/service/service-list.vue, project/ovp/frontend/ovp/store/manage/service/index.ts, project/ovp/frontend/ovp/utils/constant.ts, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> fix: 서비스 관리 버그 수정

project/ovp/server/src/main/java/com/mobigen/ovp/search/SearchService.java
=> [FAB2023-1157] fix: 검색 api query_filter 처리 오류 수정

project/ovp/frontend/common/components/base/loading/Loading.vue, project/ovp/frontend/common/components/extends/tab/Tab.vue, project/ovp/frontend/ovp/components/datamodel-creation/list/api/DataModelApiListProps.ts, project/ovp/frontend/ovp/components/datamodel-creation/list/api/data-model-api-list.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/add-transfer.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/add.vue, project/ovp/frontend/ovp/pages/portal/datamodel-creation/index.vue, project/ovp/frontend/ovp/plugins/custom-fetch-api.ts, project/ovp/frontend/ovp/store/datamodel-creation/search.ts, project/ovp/frontend/ovp/utils/constant.ts, project/ovp/server/src/main/java/com/mobigen/ovp/model_creation/ModelCreationController.java, project/ovp/server/src/main/java/com/mobigen/ovp/model_creation/ModelCreationService.java
- [FAB2023-1221](https://mobigen.atlassian.net/browse/FAB2023-1221)
- API > my-list 인피니티 스크롤 적용으로 변경
- 화면 > my-list 아코디언 → 세부 탭으로 기획 변경
- 기타 버그사항 수정
[FAB2023-1221]: https://mobigen.atlassian.net/browse/FAB2023-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1221] 데이터 생성 > 추가 모달 2차 개발

project/ovp/frontend/ovp/components/datamodel-creation/list/base/DataModelListComposition.ts, project/ovp/frontend/ovp/components/datamodel-creation/list/base/data-model-list.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/add-transfer.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/add.vue, project/ovp/frontend/ovp/pages/portal/datamodel-creation/index.vue, project/ovp/frontend/ovp/store/datamodel-creation/search.ts
- [FAB2023-1221](https://mobigen.atlassian.net/browse/FAB2023-1221)
-  추가 모달 2차 개발 항목
[FAB2023-1221]: https://mobigen.atlassian.net/browse/FAB2023-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1221] feat: 데이터 생성 > 추가 모달 2차 개발 항목

project/ovp/frontend/ovp/components/datamodel-creation/list/api/DataModelApiListComposition.ts, project/ovp/frontend/ovp/components/datamodel-creation/list/base/DataModelListComposition.ts, project/ovp/frontend/ovp/components/datamodel-creation/modal/add-transfer.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/add.vue, project/ovp/frontend/ovp/store/datamodel-creation/search.ts
- [이슈번호](이슈링크)
- 데이터 모델 생성 > 추가 모달 버그 수정
=> [FAB2023-1221] fix: 데이터 모델 생성 > 추가 모달 버그 수정

project/ovp/frontend/common/assets/css/components/_editable-group.scss, project/ovp/frontend/common/components/extends/tree/tree.scss, project/ovp/frontend/ovp/assets/css/pages/_governance.scss, project/ovp/frontend/ovp/assets/css/pages/_manage.scss, project/ovp/frontend/ovp/assets/css/pages/common/_work.scss, project/ovp/frontend/ovp/components/classification/classification-list/classificationList-modify.vue, project/ovp/frontend/ovp/components/classification/classification-list/classificationList.vue, project/ovp/frontend/ovp/components/govern/glossary/data-model.vue, project/ovp/frontend/ovp/components/govern/glossary/modal/modal-glossary-dictionary.vue, project/ovp/frontend/ovp/components/govern/glossary/modal/modal-glossary.vue, project/ovp/frontend/ovp/components/manage/service/modal/modal-service/step/step3.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1244] 09/23 버그 리스트 이슈 수정 - 퍼블리싱

project/ovp/frontend/ovp/components/govern/glossary/glossary-activities.vue, project/ovp/frontend/ovp/components/govern/glossary/glossary-info.vue, project/ovp/frontend/ovp/components/govern/glossary/glossary-list.vue, project/ovp/frontend/ovp/components/govern/glossary/glossary-table.vue, project/ovp/frontend/ovp/store/glossary/index.ts
- 용어사전 > 용어 목록 인피니티 스크롤 적용
- 용어사전 > 활동사항 목록 인피니티 스크롤 적용
- 용어목록 조회 중복호출 제거
- 활동사항 count 조회 중복호출 제거
- 용어사전 > 용어사전 목록 인피니티 스크롤 관련 코드 제거
=> fix: 용어사전 > 용어/활동사항 인피니티 스크롤 적용

project/ovp/frontend/ovp/components/manage/service/linkDetailComponent.vue, project/ovp/frontend/ovp/components/manage/service/modal/log.vue, project/ovp/frontend/ovp/layouts/default.vue, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- [FAB2023-1245](https://mobigen.atlassian.net/browse/FAB2023-1245)
- 서비스관리/ 저장소 탭에서 데이터 모델명이 displayName 으로 안나오는 문제 수정
[FAB2023-1245]: https://mobigen.atlassian.net/browse/FAB2023-1245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1245] 09/23 버그 리스트 수정

project/ovp/frontend/ovp/components/datamodel-creation/modal/add-transfer.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/add.vue, project/ovp/frontend/ovp/store/datamodel-creation/search.ts
=> [FAB2023-1213] 데이터 모델 생성 버그 수정

project/ovp/frontend/ovp/components/manage/service/service-info.vue, project/ovp/frontend/ovp/layouts/header.vue, project/ovp/frontend/ovp/pages/portal/datamodel-creation/index.vue, project/ovp/frontend/ovp/plugins/custom-fetch-api.ts, project/ovp/frontend/ovp/plugins/router.client.ts, project/ovp/frontend/ovp/store/common/menu.ts, project/ovp/frontend/ovp/store/datamodel-creation/index.ts, project/ovp/frontend/ovp/store/manage/service/index.ts
- https://mobigen.atlassian.net/browse/FAB2023-1246
- front router 권한처리
=> [FAB2023-1246] 버그리스트 이슈처리

project/ovp/server/src/main/java/com/mobigen/ovp/common/ModelConvertUtil.java
- https://mobigen.atlassian.net/browse/FAB2023-1246
- 목록 오류 수정
=> [FAB2023-1246] fix : displayName 이 없는 태그 데이터 모델에 셋팅시 발생하는 오류 수정

project/ovp/frontend/ovp/components/classification/classification-list/classificationList-modify.vue, project/ovp/frontend/ovp/components/classification/modal/classification-create.vue, project/ovp/frontend/ovp/components/classification/modal/tag-create.vue, project/ovp/frontend/ovp/components/classification/modal/tag-modify.vue, project/ovp/frontend/ovp/components/govern/category/category-add-modal.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-1242
- https://mobigen.atlassian.net/browse/FAB2023-1213
=> [FAB2023-1213] 버그리스트 이슈 처리

project/ovp/frontend/ovp/components/classification/classification-list/classificationList-modify.vue, project/ovp/frontend/ovp/components/classification/classification-list/classificationList.vue, project/ovp/frontend/ovp/store/classification/index.ts
- [FAB2023-1249](https://mobigen.atlassian.net/browse/FAB2023-1249)
- 분류 목록 항목에 텍스트 클릭시 새로고침되는 문제 해결
- 선택된 분류 목록에 표시 안되는 문제 해결
- 분류 정보(이름/설명)수정후 수정상태 닫히지 않는 문제 해결
- 분류정보 수정후 분류 목록에 선택된 상태로 유지되지 않는 문제 해결
[FAB2023-1249]: https://mobigen.atlassian.net/browse/FAB2023-1249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1249] 버그리스트 수정

project/ovp/frontend/ovp/components/search/detail-tab/default-info.vue, project/ovp/frontend/ovp/components/search/detail-tab/profiling.vue, project/ovp/frontend/ovp/components/search/detail-tab/sample.vue, project/ovp/frontend/ovp/components/search/detail-tab/schema.vue, project/ovp/frontend/ovp/layouts/default.vue, project/ovp/frontend/ovp/store/login/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/response/DataModelDetailSampleDataResponse.java
- [이슈번호](이슈링크)
- [FAB2023-1245](https://mobigen.atlassian.net/browse/FAB2023-1245)
- 회원가입 안되는 문제 수정
[FAB2023-1245]: https://mobigen.atlassian.net/browse/FAB2023-1245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1245] 09/23 버그 리스트 수정 2일차

project/ovp/frontend/common/components/extends/alert/Alert.vue, project/ovp/frontend/common/components/extends/alert/useAlert.ts, project/ovp/frontend/common/layouts/default.vue, project/ovp/frontend/common/pages/components/alert/index.vue, project/ovp/frontend/common/pages/index.vue, project/ovp/frontend/common/plugins/alert.ts, project/ovp/frontend/ovp/layouts/default.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue, project/ovp/frontend/ovp/plugins/Alert.ts
- 
- [FAB2023-1245](https://mobigen.atlassian.net/browse/FAB2023-1245)
[FAB2023-1245]: https://mobigen.atlassian.net/browse/FAB2023-1245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1245] alert, confirm 컴포넌트 추가

project/ovp/frontend/common/assets/css/components/_editable-group.scss, project/ovp/frontend/common/assets/css/components/_modal.scss, project/ovp/frontend/common/components/extends/menu-seach/menu-search.vue, project/ovp/frontend/ovp/assets/css/pages/_creation.scss, project/ovp/frontend/ovp/assets/css/pages/_governance.scss, project/ovp/frontend/ovp/components/datamodel-creation/modal/save.vue, project/ovp/frontend/ovp/components/govern/glossary/glossary-info.vue, project/ovp/frontend/ovp/components/govern/glossary/glossary-term-info.vue, project/ovp/frontend/ovp/components/govern/glossary/modal/modal-glossary-dictionary.vue, project/ovp/frontend/ovp/components/govern/glossary/modal/modal-glossary.vue, project/ovp/frontend/ovp/components/search/detail-tab/default-info.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1250] menu-search 클래스 타입 추가 작업, 버그리스트 이슈 수정

project/ovp/frontend/ovp/components/common/preview/preview.vue, project/ovp/frontend/ovp/components/search/detail-tab/lineage.vue, project/ovp/frontend/ovp/components/search/lineage/data-lineage-filter.vue, project/ovp/frontend/ovp/components/search/lineage/lineage-graph.vue, project/ovp/frontend/ovp/store/search/common.ts, project/ovp/frontend/ovp/store/search/detail/lineage/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/dto/response/DataModelDetailLineageTableResponse.java
=> feat: 탐색 상세 > 데이터 리니지 페이지 기능 구현

project/ovp/frontend/ovp/components/classification/classification-list/tagList.vue, project/ovp/frontend/ovp/components/classification/modal/tag-modify.vue, project/ovp/frontend/ovp/store/classification/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/classification/ClassificationTagController.java, project/ovp/server/src/main/java/com/mobigen/ovp/classification/ClassificationTagService.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ClassificationTagsClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/dto/classification/tag/EditTagRequest.java
- [FAB2023-1247](https://mobigen.atlassian.net/browse/FAB2023-1247)
- 태그 수정 서버개발
- 태그 수정 화면개발
=> [FAB2023-1247] 거버넌스 분류 태그 수정 API / 화면 개발

project/ovp/frontend/ovp/components/govern/glossary/data-model.vue
- [FAB2023-1248](https://mobigen.atlassian.net/browse/FAB2023-1248)
[FAB2023-1248]: https://mobigen.atlassian.net/browse/FAB2023-1248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1248] 버그리스트 수정

project/ovp/frontend/ovp/components/search/detail-default.vue, project/ovp/server/src/main/java/com/mobigen/ovp/overview/OverviewController.java, project/ovp/server/src/main/java/com/mobigen/ovp/overview/OverviewService.java, project/ovp/server/src/main/java/com/mobigen/ovp/overview/client/MonitoringClient.java, project/ovp/server/src/main/resources/application.yml
- [이슈번호](이슈링크)
- [FAB2023-1245](https://mobigen.atlassian.net/browse/FAB2023-1245)
- Overview API 추가
[FAB2023-1245]: https://mobigen.atlassian.net/browse/FAB2023-1245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1245] Overview API 추가

project/ovp/frontend/ovp/pages/portal/govern/category/index.vue
- https://mobigen.atlassian.net/browse/FAB2023-1242
- https://mobigen.atlassian.net/browse/FAB2023-1213
=> [FAB2023-1213] 거버넌스>카테고리 공통 alert 추가

project/ovp/frontend/common/assets/css/abstracts/_overlay.scss, project/ovp/frontend/common/assets/css/base.scss, project/ovp/frontend/common/assets/css/components/_editable-group.scss, project/ovp/frontend/common/assets/css/components/_modal.scss, project/ovp/frontend/common/assets/css/themes/_set-color.scss, project/ovp/frontend/common/components/base/alert/alert.scss, project/ovp/frontend/common/components/base/loading/Loading.scss, project/ovp/frontend/common/components/extends/alert/Alert.vue, project/ovp/frontend/common/pages/design-guide/pages/guide-alert.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1251] 얼럿 스타일 추가 - 퍼블리싱

project/ovp/frontend/ovp/layouts/sidebar.vue, project/ovp/frontend/ovp/middleware/router.global.ts, project/ovp/frontend/ovp/pages/portal/my-page/index.vue, project/ovp/frontend/ovp/plugins/router.client.ts, project/ovp/frontend/ovp/store/common/menu.ts
- 마이페이지로 이동이 안되는 이슈 처리
- 사용자관리 페이지에서 사용자 마이페이지로 이동시, 관리메뉴 하이라이팅 처리
- 사용자관리 페이지에서 사용자 마이페이지로 이동한 후, 헤더의 마이페이지를 클릭해 다시 이동할때 query 값에 따라 데이터가 재설정 되지 않는 이슈 처리
=> feat: 마이페이지 이동 안되는 이슈 처리

project/ovp/frontend/ovp/components/classification/classification-list/classificationList-modify.vue
- [FAB2023-1249](https://mobigen.atlassian.net/browse/FAB2023-1249)
- 분류 name값 변경시, validation통과하지 못하면 edit 열린상태 및 수정값 유지 & 수정API넘어가지 않도록 변경
[FAB2023-1249]: https://mobigen.atlassian.net/browse/FAB2023-1249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1249] 버그리스트 이슈처리

project/ovp/frontend/ovp/components/search/data-filter.vue, project/ovp/frontend/ovp/layouts/header.vue, project/ovp/frontend/ovp/package-lock.json, project/ovp/frontend/ovp/package.json, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/frontend/ovp/plugins/persistedstate.client.ts, project/ovp/frontend/ovp/store/layout/header.ts, project/ovp/frontend/ovp/store/search/common.ts
- 탐색페이지 - 탐색 상세페이지에서 넘어온 경우에만 검색 조건 유지
=> feat: 탐색페이지 검색 조건 유지

project/ovp/frontend/ovp/components/classification/classification-list/classificationList-modify.vue, project/ovp/frontend/ovp/components/classification/classification-list/tagList.vue
- [FAB2023-1249](https://mobigen.atlassian.net/browse/FAB2023-1249)
- confirm, alert 기능 변경 작업
[FAB2023-1249]: https://mobigen.atlassian.net/browse/FAB2023-1249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1249] 버그리스트 이슈처리 

project/ovp/frontend/ovp/components/govern/glossary/data-model.vue, project/ovp/frontend/ovp/components/govern/glossary/glossary-info.vue, project/ovp/frontend/ovp/components/govern/glossary/glossary-table.vue, project/ovp/frontend/ovp/components/govern/glossary/glossary-term-info.vue, project/ovp/frontend/ovp/components/manage/service/service-info.vue, project/ovp/frontend/ovp/type/common.ts
- [FAB2023-1248](https://mobigen.atlassian.net/browse/FAB2023-1248)
[FAB2023-1248]: https://mobigen.atlassian.net/browse/FAB2023-1248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1248] 버그 수정

project/ovp/frontend/ovp/store/my-page/myPageStore.ts
- https://mobigen.atlassian.net/browse/FAB2023-1246
- 마이페이지 접속시 화면 표시 안됨 오류 수정
=> [FAB2023-1246] 버그리스트 수정

project/ovp/frontend/ovp/components/manage/service/modal/log.vue
=> [FAB2023-1202] fix : 서비스 > 수집 > 로그 복사 안됨 수정

project/ovp/frontend/ovp/assets/css/pages/_search-detail.scss, project/ovp/frontend/ovp/pages/_pub/search-detail/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1227] 비정형 데이터 상세 추가작업 퍼블리싱

project/ovp/frontend/ovp/store/datamodel-creation/save.ts
=> [FAB2023-1270] fix : 데이터 모델 생성 -> 저장 모달 오류 수정

project/ovp/frontend/ovp/pages/portal/search/detail/index.vue
=> [FAB2023-1270] feat: 탐색 - 상세 '연관데이터모델 시각화' 탭 alert 추가 처리

project/ovp/frontend/ovp/components/manage/service/overview.vue
- https://mobigen.atlassian.net/browse/FAB2023-1274
- https://mobigen.atlassian.net/browse/FAB2023-1213
=> [FAB2023-1213] 버그리스트 이슈처리

project/ovp/frontend/ovp/components/manage/service/ingestions.vue, project/ovp/frontend/ovp/components/manage/service/modal/collection/modal-collection.vue, project/ovp/frontend/ovp/store/manage/service/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ServicesClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageController.java, project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- [FAB2023-1272](https://mobigen.atlassian.net/browse/FAB2023-1272)
[FAB2023-1272]: https://mobigen.atlassian.net/browse/FAB2023-1272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1272] 버그리스트 이슈 수정

project/ovp/frontend/common/assets/css/abstracts/_fonts.scss, project/ovp/frontend/common/assets/css/tailwind/_tailwind-base.scss
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1275] 콘솔 폰트 cdn 오류 수정

project/ovp/server/src/main/java/com/mobigen/ovp/service_manager/ServiceManageService.java
- [FAB2023-1213](https://mobigen.atlassian.net/browse/FAB2023-1213)
- [FAB2023-1273](https://mobigen.atlassian.net/browse/FAB2023-1273)
- 관리 > 서비스 > 상세 정보의 태그 추가 및 수정 안되는 버그 해결
[FAB2023-1213]: https://mobigen.atlassian.net/browse/FAB2023-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-1273]: https://mobigen.atlassian.net/browse/FAB2023-1273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> "[FAB2023-1213] fix : 관리 > 서비스 > 상세 태그 추가& 수정 안되는 버그 해결"

project/ovp/frontend/ovp/pages/portal/my-page/index.vue
- [FAB2023-1213](https://mobigen.atlassian.net/browse/FAB2023-1213)
- [FAB2023-1273](https://mobigen.atlassian.net/browse/FAB2023-1273)
- 사용자 정보조회오류 exception되는 문제 해결
[FAB2023-1213]: https://mobigen.atlassian.net/browse/FAB2023-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-1273]: https://mobigen.atlassian.net/browse/FAB2023-1273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1213] 사용자 정보조회오류 exception되는 문제 해결

project/ovp/frontend/ovp/pages/portal/my-page/index.vue, project/ovp/frontend/ovp/store/my-page/myPageStore.ts
- [이슈번호](이슈링크)
- 아래 이유로 원복함
- 메인페이지 api 로 변경했을때 검색어 처리 안됨
- paging(infinite scroll) 처리 안됨
=> [FAB2023-1270] fix : 마이페이지 -> 나의 북마크 수정내용 원복

project/ovp/frontend/ovp/components/search/detail-default.vue, project/ovp/frontend/ovp/pages/portal/govern/category/index.vue
=> [FAB2023-1270] fix : $confirm 관련 코드 수정

project/ovp/frontend/ovp/components/datamodel-creation/modal/save.vue, project/ovp/frontend/ovp/store/datamodel-creation/save.ts
=> [FAB2023-1213] ovp 버그 수정

project/ovp/frontend/ovp/assets/css/pages/_creation.scss, project/ovp/frontend/ovp/components/datamodel-creation/modal/add-detail-grid.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/add.vue, project/ovp/frontend/ovp/pages/_pub/creation/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1224] refactor: 데이터모델 생성 / 추천데이터 - 퍼블리싱

project/ovp/frontend/ovp/components/search/common/custom-knowledge-graph.vue, project/ovp/frontend/ovp/components/search/common/graph/category-graph.vue, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/frontend/ovp/pages/portal/search/top-bar.vue, project/ovp/frontend/ovp/store/search/common.ts
- https://mobigen.atlassian.net/browse/FAB2023-1261
- https://mobigen.atlassian.net/browse/FAB2023-1897
=> [FAB2023-898] 탐색(시각화보기) - 화면 개발 2 

project/ovp/frontend/common/components/extends/tree/Tree.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue
- [FAB2023-1296](https://mobigen.atlassian.net/browse/FAB2023-1296)
[FAB2023-1296]: https://mobigen.atlassian.net/browse/FAB2023-1296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1296] 버그리스트 처리

project/ovp/frontend/ovp/assets/css/pages/_search.scss, project/ovp/frontend/ovp/assets/css/pages/common/_graph.scss, project/ovp/frontend/ovp/components/manage/service/overview.vue, project/ovp/frontend/ovp/pages/_pub/creation/index.vue, project/ovp/frontend/ovp/pages/_pub/govern/glossary/index.vue, project/ovp/frontend/ovp/pages/_pub/govern/tags/index.vue, project/ovp/frontend/ovp/pages/_pub/manage/service/index.vue, project/ovp/frontend/ovp/pages/_pub/manage/user/index.vue, project/ovp/frontend/ovp/pages/_pub/search-detail/index.vue
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1230] overview 수집 일시 위치 조정 - 퍼블리싱

project/ovp/frontend/ovp/assets/css/pages/_search-detail.scss, project/ovp/frontend/ovp/components/search/detail-tab/query.vue, project/ovp/frontend/ovp/store/search/detail/index.ts
=> [FAB2023-1295] 탐색 - 상세 - 쿼리 구현

project/ovp/frontend/ovp/store/manage/service/overview/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/overview/OverviewService.java, project/ovp/server/src/main/java/com/mobigen/ovp/overview/client/MonitoringClient.java
=> [FAB2023-1213] 모니터링 서비스 api 수정에 따른 overview 수정

project/ovp/frontend/common/components/extends/menu-seach/MenuSearchComposition.ts, project/ovp/frontend/ovp/assets/css/pages/_search.scss, project/ovp/frontend/ovp/assets/css/pages/common/_graph.scss, project/ovp/frontend/ovp/components/govern/glossary/data-model.vue, project/ovp/frontend/ovp/components/govern/glossary/glossary-activities.vue, project/ovp/frontend/ovp/pages/portal/govern/index.vue, project/ovp/frontend/ovp/pages/portal/manage/user/index.vue, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/frontend/ovp/store/datamodel-creation/search.ts, project/ovp/frontend/ovp/store/search/common.ts, project/ovp/frontend/ovp/store/user/userStore.ts, project/ovp/frontend/ovp/utils/constant.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/ModelConvertUtil.java
- https://mobigen.atlassian.net/browse/FAB2023-1290
fix : 목록에서 카테고리 표시 안됨 수정
=> [FAB2023-1290] 패키지 용 버그 수정

project/ovp/frontend/common/components/extends/menu-seach/MenuSearchComposition.ts, project/ovp/frontend/ovp/components/govern/glossary/data-model.vue, project/ovp/frontend/ovp/components/govern/glossary/glossary-activities.vue, project/ovp/frontend/ovp/components/manage/service/modal/log.vue, project/ovp/frontend/ovp/pages/portal/govern/index.vue, project/ovp/frontend/ovp/pages/portal/manage/user/index.vue, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/frontend/ovp/store/datamodel-creation/search.ts, project/ovp/frontend/ovp/store/search/common.ts, project/ovp/frontend/ovp/store/user/userStore.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/ModelConvertUtil.java
=> TTA -> sprint26 수정 사항 반영

project/ovp/frontend/ovp/components/govern/glossary/data-model.vue
=> [FAB2023-1290] fix : 테스트 코드 삭제

project/ovp/frontend/ovp/assets/css/pages/common/_graph.scss, project/ovp/frontend/ovp/components/search/common/custom-knowledge-graph.vue, project/ovp/frontend/ovp/components/search/common/graph/category-graph.vue, project/ovp/frontend/ovp/components/search/data-filter.vue, project/ovp/frontend/ovp/layouts/header.vue, project/ovp/frontend/ovp/package.json, project/ovp/frontend/ovp/pages/portal/search/index.vue, project/ovp/frontend/ovp/pages/portal/search/top-bar.vue, project/ovp/frontend/ovp/store/search/common.ts
- https://mobigen.atlassian.net/browse/FAB2023-1293
=> [FAB2023-898] 시각화 그래프 구현 - 개발

project/ovp/frontend/ovp/store/search/common.ts
- 
https://mobigen.atlassian.net/browse/FAB2023-1290
=> [FAB2023-1290] fix : 탐색 > 상세 > 목록 표시 안됨 수정

project/ovp/frontend/ovp/pages/portal/search/detail/index.vue
=> [FAB2023-1213] 모델상세 - 스토리지 > 확장자에 따른 탭 노출 분기 처리

project/ovp/frontend/ovp/components/search/detail-tab/recommend-model.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue, project/ovp/frontend/ovp/store/search/detail/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/RecommendClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java, project/ovp/server/src/main/resources/application.yml
- [FAB2023-1298](https://mobigen.atlassian.net/browse/FAB2023-1298) 
[FAB2023-1298]: https://mobigen.atlassian.net/browse/FAB2023-1298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1298] feat: 추천 데이터 개발

project/ovp/frontend/ovp/components/datamodel-creation/execute-query.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/save.vue, project/ovp/frontend/ovp/pages/portal/datamodel-creation/index.vue, project/ovp/frontend/ovp/store/datamodel-creation/index.ts, project/ovp/frontend/ovp/store/datamodel-creation/save.ts, project/ovp/frontend/ovp/utils/constant.ts, project/ovp/server/src/main/java/com/mobigen/framework/exception/GlobalExceptionHandler.java, project/ovp/server/src/main/java/com/mobigen/ovp/model_creation/ModelCreationController.java, project/ovp/server/src/main/java/com/mobigen/ovp/model_creation/ModelCreationService.java
=> [FAB2023-1213] 데이터 모델 생성 > '저장' 모달 validation 추가 외

project/ovp/frontend/ovp/components/search/detail-tab/default-info.vue, project/ovp/frontend/ovp/components/search/detail-tab/sample.vue, project/ovp/frontend/ovp/pages/portal/search/detail/index.vue, project/ovp/frontend/ovp/store/search/detail/index.ts, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ContainerClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/common/openmete_client/ContainersClient.java, project/ovp/server/src/main/java/com/mobigen/ovp/container/ContainerController.java, project/ovp/server/src/main/java/com/mobigen/ovp/container/ContainerService.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailController.java, project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java
=> [FAB2023-1213] 모델상세 > 비정형데이터(특정확장자들) 기본정보,샘플데이터 탭 내용 표시 처리

project/ovp/frontend/ovp/components/search/common/graph/category-graph.vue, project/ovp/frontend/ovp/components/search/data-filter.vue, project/ovp/frontend/ovp/store/search/common.ts
- https://mobigen.atlassian.net/browse/FAB2023-1293
- 툴팁 추가
- 분기된 뎁스 데이터 목록 다시 가져오기
=> [FAB2023-898] 탐색(시각화보기) - 기능 구현 (툴팁, 분기된 뎁스 데이터 다시 불러오기)

project/ovp/frontend/ovp/components/govern/glossary/glossary-info.vue, project/ovp/frontend/ovp/components/manage/service/service-info.vue
=> [FAB2023-1213] 상위뎁스 표시되도록 수정

project/ovp/frontend/ovp/assets/css/pages/_search-detail.scss
- [이슈번호](이슈링크)
- [이슈번호](이슈링크)
- 수정 내용 1
- 수정 내용 2
=> [FAB2023-1311] 상세 / 추천데이터 레이아웃 틀어짐 이슈 - 퍼블리싱

project/ovp/frontend/ovp/plugins/custom-fetch-api.ts, project/ovp/server/src/main/java/com/mobigen/framework/security/JwtFilter.java
- [FAB2023-1310]([FAB2023-1310](https://mobigen.atlassian.net/browse/FAB2023-1310))
- AccessToken 만료 시 API redirect처리 불가 이슈 수정
[FAB2023-1310]: https://mobigen.atlassian.net/browse/FAB2023-1310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-1310]: https://mobigen.atlassian.net/browse/FAB2023-1310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1310] fix: AccessToken 세션 타임 아웃 버그 수정

project/ovp/frontend/ovp/components/search/common/graph/category-graph.vue, project/ovp/frontend/ovp/store/search/common.ts
- https://mobigen.atlassian.net/browse/FAB2023-1294
- https://mobigen.atlassian.net/browse/FAB2023-897
=> [FAB2023-897] 그래프 뷰 - 노드 상태 별 스타일 설정 구현

project/ovp/frontend/ovp/components/search/common/graph/category-graph.vue, project/ovp/frontend/ovp/package.json
- https://mobigen.atlassian.net/browse/FAB2023-1304
- https://mobigen.atlassian.net/browse/FAB2023-897
=> [FAB2023-897] 시각화 그래프 구현 - 개선된 기능 반영

project/ovp/frontend/ovp/components/search/common/graph/category-graph.vue
- https://mobigen.atlassian.net/browse/FAB2023-1274
- https://mobigen.atlassian.net/browse/FAB2023-1213
=> [FAB2023-1213] 20241115_06 탐색 > 시각화보기 - 상세정보/데이터 모델 드롭다운 이슈처리 

project/ovp/frontend/ovp/components/common/preview/preview.vue, project/ovp/frontend/ovp/components/common/resource-box/resource-box-common-props.ts, project/ovp/frontend/ovp/components/common/resource-box/resource-box.vue, project/ovp/frontend/ovp/components/datamodel-creation/modal/add.vue, project/ovp/frontend/ovp/components/search/detail-tab/recommend-model.vue, project/ovp/frontend/ovp/store/datamodel-creation/search.ts, project/ovp/frontend/ovp/utils/constant.ts
- [FAB2023-1213](https://mobigen.atlassian.net/browse/FAB2023-1213)
- [FAB2023-1328](https://mobigen.atlassian.net/browse/FAB2023-1328)
[FAB2023-1213]: https://mobigen.atlassian.net/browse/FAB2023-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAB2023-1328]: https://mobigen.atlassian.net/browse/FAB2023-1328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FAB2023-1328] fix: 데이터모델추가 > 추천데이터 화면 수정

project/ovp/frontend/ovp/components/datamodel-creation/modal/add.vue, project/ovp/frontend/ovp/store/datamodel-creation/search.ts, project/ovp/frontend/ovp/utils/constant.ts
- 선택한 데이터 모델 영역 이동시 tab 리셋(첫번째 탭 표시되도록 처리)
- 추천 데이터 항목 없을때 noty 메시지 표시 추가
- 데이터 모델 추가 모달에서 추천데이터 항목 명 변경 (추천 데이터 -> 추천 데이터 모델)
- https://mobigen.atlassian.net/browse/FAB2023-1313
=> [FAB2023-1313] fix : 데이터 모델 이동시 tab 리셋 코드 추가 외

project/ovp/frontend/ovp/pages/portal/search/top-bar.vue, project/ovp/frontend/ovp/store/search/common.ts, project/ovp/frontend/ovp/utils/constant.ts
- https://mobigen.atlassian.net/browse/FAB2023-1332
- 탐색 > 목록 > 연관도순 추가 및 기본값 설정
=> [FAB2023-1332] feat : 탐색 > 목록 > 연관도순 추가 및 기본값 설정

project/ovp/server/src/main/java/com/mobigen/ovp/search_detail/SearchDetailService.java
- https://mobigen.atlassian.net/browse/FAB2023-1336
- clustering -> embedding
=> [FAB2023-1336] feat : 추천데이터 조회 호출 코드 수정
